const items=[['Overview','home'],['Device','device'],['Audio','audio'],['Wake Word','mic'],['LED & Buttons','sun'],['Network','wifi'],['Privacy','shield'],['Integrations','puzzle'],['System','gear'],['Logs','log'],['About','info']];
const descriptions={Overview:'Your LibreEcho at a glance',Device:'Identity, hardware and power controls',Audio:'Playback, microphone and volume controls','Wake Word':'Configure local wake-word detection','LED & Buttons':'Customise light-ring behaviour and controls',Network:'Wi-Fi, addressing and connectivity',Privacy:'Local processing and data retention controls',Integrations:'Connect services and home automation',System:'Updates, backup and advanced settings',Logs:'Diagnostics and troubleshooting',About:'Project, licences and version information'};
const nav=document.querySelector('#nav'),content=document.querySelector('#content');
items.forEach(([name,icon],i)=>{const b=document.createElement('button');b.className='nav-item'+(i===0?' active':'');b.innerHTML=`<svg><use href="#${icon}"></use></svg><span>${name}</span>`;b.onclick=()=>showPage(name,b);nav.appendChild(b)});
const shortcuts=[['Audio','audio','Configure volume, audio output and sound settings.','green'],['Wake Word','mic','Manage wake word, sensitivity and detection settings.','purple'],['LED & Buttons','sun','Customise LED colours, brightness and button actions.','blue'],['Network','wifi','Configure Wi-Fi, Ethernet and network settings.','sky'],['Privacy','shield','Control data, permissions and privacy settings.','green'],['Integrations','puzzle','Manage services, automations and third-party apps.','orange'],['System','gear','System updates, backup, restore and advanced options.','grey'],['Logs','log','View system logs and diagnostic information.','orange']];
function overview(){content.innerHTML=`<div class="grid-top"><div class="panel hero"><h2>LibreEcho</h2><p>Open source voice assistant<br>built for privacy and freedom.</p><img class="device-img" src="device.png"><div class="hero-actions"><button class="primary-btn">View Docs ↗</button><button class="secondary-btn">♡ &nbsp;Support</button></div></div><div class="panel status-panel"><h3>System Status</h3>${metric('device','CPU Load','18%','28%')}${metric('device','Memory','412 MB / 1.8 GB','45%')}${metric('device','Storage','2.1 GB / 14.8 GB','19%')}${metric('sun','Temperature','48 °C','33%')}${metric('wifi','Wi-Fi','Connected','100%',true)}${metric('info','Internet','Connected','100%',true)}</div></div><div class="cards">${shortcuts.map(x=>`<div class="panel shortcut" data-page="${x[0]}"><svg class="${x[3]}"><use href="#${x[1]}"></use></svg><div><h3>${x[0]}</h3><p>${x[2]}</p></div><span class="arrow">›</span></div>`).join('')}</div><div class="panel community"><div class="community-logo">◉</div><div><h3>Open Source. Community Driven.</h3><p>LibreEcho is built by the community, for the community.<br>Join us in building a better, open voice assistant.</p></div><div class="push"><button class="outline-btn">Join Community</button><button class="secondary-btn">● &nbsp; Contribute on GitHub</button></div></div>`;document.querySelectorAll('[data-page]').forEach(c=>c.onclick=()=>{const name=c.dataset.page;showPage(name,[...nav.children].find(b=>b.innerText===name))})}
function metric(icon,label,value,width,connected=false){return `<div class="metric"><svg><use href="#${icon}"></use></svg><span>${label}</span><span class="value ${connected?'connected':''}">${value}</span><div class="bar"><i style="width:${width}"></i></div></div>`}
function settingsPage(name){const map={
'Device':`<div class="panel setting-panel"><h3>Device identity</h3>${field('Device name','Kitchen LibreEcho')}${field('Location','Kitchen')}<div class="switch-row"><span>Start automatically after power loss</span><div class="switch on"></div></div></div><div class="panel setting-panel"><h3>Power</h3><div class="switch-row"><span>Performance mode</span><div class="switch"></div></div><div class="switch-row"><span>Automatic sleep overnight</span><div class="switch on"></div></div><button class="save-btn">Save changes</button></div>`,
'Audio':`<div class="panel setting-panel"><h3>Output</h3>${range('Master volume',64)}${range('Bass',52)}${range('Treble',56)}<div class="switch-row"><span>Startup sound</span><div class="switch on"></div></div></div><div class="panel setting-panel"><h3>Microphones</h3>${range('Microphone gain',70)}<div class="switch-row"><span>Hardware mute button enabled</span><div class="switch on"></div></div><div class="switch-row"><span>Acoustic echo cancellation</span><div class="switch on"></div></div></div>`,
'Wake Word':`<div class="panel setting-panel"><h3>Wake-word engine</h3>${select('Active wake word',['LibreEcho','Computer','Echo','Custom model'])}${range('Detection sensitivity',68)}<div class="switch-row"><span>Play acknowledgement tone</span><div class="switch on"></div></div></div><div class="panel setting-panel"><h3>Local detection</h3><p style="color:#aebbc7">Wake-word processing runs locally and does not send microphone audio to the network.</p><div class="switch-row"><span>Require wake word before commands</span><div class="switch on"></div></div><div class="switch-row"><span>Allow follow-up mode</span><div class="switch"></div></div></div>`,
'LED & Buttons':`<div class="panel setting-panel"><h3>Light ring</h3><div class="field"><label>Boot LED colour</label><div class="colour-row"><i class="colour selected" style="background:#48d876"></i><i class="colour" style="background:#48b9ff"></i><i class="colour" style="background:#a873ef"></i><i class="colour" style="background:#ff9f32"></i><i class="colour" style="background:#fff"></i></div></div>${range('Brightness',72)}<div class="switch-row"><span>Night-time dimming</span><div class="switch on"></div></div></div><div class="panel setting-panel"><h3>Button actions</h3>${select('Action button',['Start listening','Run automation','Play / pause','Disabled'])}${select('Long press',['Open pairing mode','Reboot device','Toggle privacy mode'])}</div>`,
'Network':`<div class="panel setting-panel"><h3>Wireless network</h3>${select('Wi-Fi network',['LibreNet-5G','LibreNet-IoT','Add another network…'])}${field('IPv4 address','192.168.10.42')}<div class="switch-row"><span>Use DHCP</span><div class="switch on"></div></div></div><div class="panel setting-panel"><h3>Remote access</h3><div class="switch-row"><span>Enable local web interface</span><div class="switch on"></div></div><div class="switch-row"><span>Enable SSH</span><div class="switch"></div></div>${field('Hostname','libreecho-kitchen.local')}</div>`,
'Privacy':`<div class="panel setting-panel"><h3>Processing</h3><div class="switch-row"><span>Local speech recognition only</span><div class="switch on"></div></div><div class="switch-row"><span>Store command history</span><div class="switch"></div></div><div class="switch-row"><span>Anonymous diagnostics</span><div class="switch"></div></div></div><div class="panel setting-panel"><h3>Retention</h3>${select('Diagnostic log retention',['24 hours','7 days','30 days','Never retain'])}<button class="secondary-btn">Delete stored data</button></div>`};return `<div class="settings-grid">${map[name]||generic(name)}</div>`}
function generic(name){return `<div class="panel setting-panel"><h3>${name}</h3><p style="color:#aebbc7">This prototype page demonstrates the navigation and visual system for the future LibreEcho control centre.</p><div class="switch-row"><span>Enable ${name.toLowerCase()}</span><div class="switch on"></div></div><button class="save-btn">Save changes</button></div><div class="panel setting-panel"><h3>Status</h3><p class="connected">All services operational</p><p style="color:#aebbc7">Configuration changes are stored locally on the device.</p></div>`}
function field(label,value){return `<div class="field"><label>${label}</label><input value="${value}"></div>`}function select(label,vals){return `<div class="field"><label>${label}</label><select>${vals.map(v=>`<option>${v}</option>`).join('')}</select></div>`}function range(label,val){return `<div class="field"><label>${label}: <span>${val}%</span></label><input type="range" value="${val}"></div>`}
function showPage(name,button){document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));button?.classList.add('active');document.querySelector('#page-title').textContent=name;document.querySelector('#page-subtitle').textContent=descriptions[name];name==='Overview'?overview():content.innerHTML=settingsPage(name);wire()}
function wire(){document.querySelectorAll('.switch').forEach(s=>s.onclick=()=>s.classList.toggle('on'));document.querySelectorAll('.colour').forEach(c=>c.onclick=()=>{document.querySelectorAll('.colour').forEach(x=>x.classList.remove('selected'));c.classList.add('selected')});document.querySelectorAll('.save-btn').forEach(b=>b.onclick=toast)}
function toast(){const t=document.querySelector('#toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1400)}
document.querySelector('#reboot').onclick=()=>{document.querySelector('#toast').textContent='Reboot requested';toast()};document.querySelector('#theme').onclick=()=>document.body.classList.toggle('light');overview();
