"""Regenerate wire fixtures using already-installed pinned protobuf classes.
The checked-in header is independently schema-derived until this command has
been run with the approved pinned client. Never downloads or installs tools.
"""
import importlib.metadata,pathlib,sys,re
from aioesphomeapi import api_pb2 as pb
assert importlib.metadata.version('aioesphomeapi')=='46.2.0'
vectors={
 'hello_request':pb.HelloRequest(client_info='fixture',api_version_major=1,api_version_minor=14),
 'subscribe_voice':pb.SubscribeVoiceAssistantRequest(subscribe=True,flags=4),
 'switch_mute':pb.SwitchCommandRequest(key=2,state=True),
 'api_audio':pb.VoiceAssistantAudio(data=b'\x34\x12\x78\x56',end=True),
 'set_key':pb.NoiseEncryptionSetKeyRequest(key=bytes(range(32))),
}
lines=['/* Generated by aioesphomeapi 46.2.0; synthetic public fixtures. */','#ifndef LE_ESPHOME_GOLDENS_H','#define LE_ESPHOME_GOLDENS_H']
for name,msg in vectors.items():
 data=msg.SerializeToString(deterministic=True);lines.append('static const unsigned char golden_'+name+'[]={'+','.join('0x%02x'%v for v in data)+'};')
lines+=['#endif',''];path=pathlib.Path(__file__).with_name('test_esphomed_goldens.h')
if '--check' in sys.argv:
 source=path.read_text()
 for name,msg in vectors.items():
  match=re.search(r'golden_'+name+r'\[\]=\{([^}]+)\}',source);assert match,name
  expected=bytes(int(value.strip(),16) for value in match.group(1).split(','));assert msg.SerializeToString(deterministic=True)==expected,name
 print('Pinned protobuf serialization matches checked-in vectors: PASS')
else:path.write_text('\n'.join(lines));print('Pinned protobuf goldens generated:',path)
