'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={page:'Overview',csrf:'libreecho-local',timer:null,data:{},busy:false};
const items=[['Overview','home'],['Device','device'],['Audio','audio'],['Wake Word','mic'],['LED & Buttons','sun'],['Network','wifi'],['Privacy','shield'],['Integrations','puzzle'],['System','gear'],['Logs','log'],['About','info']];
const descriptions={Overview:'Your LibreEcho at a glance',Device:'Identity, hardware and power controls',Audio:'Playback, microphone and volume controls','Wake Word':'Configure local wake-word detection','LED & Buttons':'Customise light-ring behaviour and controls',Network:'Wi-Fi, addressing and connectivity',Privacy:'Local processing and data retention controls',Integrations:'Connect services and home automation',System:'Updates, backup and advanced settings',Logs:'Diagnostics and troubleshooting',About:'Project, licences and version information'};
const nav=$('#nav'),content=$('#content');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(path,opt={}){const headers={'Accept':'application/json',...(opt.body?{'Content-Type':'application/json','X-LibreEcho-CSRF':state.csrf}:{}),...(opt.headers||{})};const res=await fetch('/api/v1'+path,{...opt,headers});let body;try{body=await res.json()}catch(_){throw new Error('The device returned an unreadable response')}if(!res.ok||!body.ok)throw new Error(body.error?.message||`Request failed (${res.status})`);return body.data}
function toast(message,error=false){const t=$('#toast');t.textContent=message;t.classList.toggle('error',error);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function panel(title,body,extra=''){return `<section class="panel setting-panel ${extra}"><h3>${title}</h3>${body}</section>`}
function field(label,value,id,type='text',extra=''){return `<label class="field"><span>${label}</span><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function range(label,value,id){return `<label class="field range-field"><span>${label}: <output>${value}%</output></span><input id="${id}" type="range" min="0" max="100" value="${value}"></label>`}
function toggle(label,on,id,disabled=false){return `<label class="switch-row"><span>${label}</span><input class="toggle-input" id="${id}" type="checkbox" ${on?'checked':''} ${disabled?'disabled':''}><span class="switch" aria-hidden="true"></span></label>`}
function select(label,value,id,values){return `<label class="field"><span>${label}</span><select id="${id}">${values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`}
function action(label,id,kind='secondary-btn'){return `<button class="${kind}" id="${id}">${label}</button>`}
function unsupported(msg){return `<div class="notice unsupported"><strong>Not supported</strong><span>${esc(msg)}</span></div>`}
function errorView(e){content.innerHTML=panel('Unable to load this section',`<div class="empty-state"><p>${esc(e.message)}</p>${action('Try again','retry','primary-btn')}</div>`);$('#retry').onclick=()=>render()}
function metric(icon,label,value,percent,connected=false){return `<div class="metric"><svg><use href="#${icon}"></use></svg><span>${label}</span><span class="value ${connected?'connected':''}">${esc(value)}</span><div class="bar"><i style="width:${Math.max(0,Math.min(100,percent))}%"></i></div></div>`}
function uptime(s){s=Math.max(0,Number(s)||0);const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return `${d?d+'d ':''}${h}h ${m}m`}
function rgb(c){return `rgb(${c.r}, ${c.g}, ${c.b})`}
function bindRange(){ $$('.range-field input').forEach(el=>el.oninput=()=>el.parentElement.querySelector('output').textContent=el.value+'%') }
function setBusy(b){state.busy=b;$$('button,input,select',content).forEach(x=>x.disabled=b)}
async function mutate(path,data,message,headers={}){if(state.busy)return;setBusy(true);try{await api(path,{method:'PUT',body:JSON.stringify(data),headers});toast(message);await render()}catch(e){toast(e.message,true);await render()}finally{setBusy(false)}}
async function post(path,data={},message='Action accepted',headers={}){if(state.busy)return;setBusy(true);try{const r=await api(path,{method:'POST',body:JSON.stringify(data),headers});toast(message);await render();return r}catch(e){toast(e.message,true);await render()}finally{setBusy(false)}}
function power(path,name){if(!confirm(`${name} this LibreEcho device?`))return;post(`/system/${path}`,{},`${name} requested`,{'X-LibreEcho-Confirm':'confirm-device-action'})}
async function overview(){const [s,n,a,l,d]=await Promise.all([api('/status'),api('/network'),api('/audio').catch(e=>({unsupported:e.message})),api('/led').catch(e=>({unsupported:e.message})),api('/device')]);state.data.status=s;$('#backend-badge').textContent=s.backend+(s.simulated?' · simulated':'');$('#backend-badge').className='backend-badge '+s.backend;$('#device-online').innerHTML=`<span></span>${esc(s.device_state)}`;$('#sidebar-uptime').textContent='Uptime: '+uptime(s.uptime_seconds);$('#sidebar-version').textContent=d.os_version;content.innerHTML=`<div class="grid-top"><div class="panel hero"><div class="sim-label">${s.simulated?'SIMULATED DEVICE':'LIVE DEVICE'}</div><h2>LibreEcho</h2><p>Open source voice assistant<br>built for privacy and freedom.</p><img class="device-img" src="/assets/device.png" alt="Amazon Echo device"><div class="hero-actions">${action('Device details','device-details','primary-btn')}${action('Refresh','refresh')}</div></div><div class="panel status-panel"><h3>System Status</h3>${metric('device','CPU Load',s.cpu_percent+'%',s.cpu_percent)}${metric('device','Memory',`${s.memory_used_mb} / ${s.memory_total_mb} MB`,s.memory_percent)}${metric('device','Storage',`${s.storage_used_mb} / ${s.storage_total_mb} MB`,s.storage_percent)}${metric('sun','Temperature',s.temperature_c+' °C',s.temperature_c)}${metric('wifi','Wi-Fi',n.state,n.signal,n.state==='connected')}${metric('info','Internet',n.internet?'Reachable':'Unavailable',n.internet?100:0,n.internet)}</div></div><div class="cards">${items.slice(2,10).map(([name,icon],i)=>`<button class="panel shortcut" data-page="${name}"><svg class="${['green','purple','blue','sky','green','orange','grey','orange'][i]}"><use href="#${icon}"></use></svg><span><strong>${name}</strong><small>${descriptions[name]}</small></span><span class="arrow">›</span></button>`).join('')}</div><div class="panel community"><img src="/assets/mark.svg" alt="" class="community-mark"><div><h3>Open Source. Community Driven.</h3><p>Configuration stays on your device. ${s.simulated?'This development session uses deterministic mock-capable hardware state.':'Values shown come from the Linux backend.'}</p></div></div>`;$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#device-details').onclick=()=>showPage('Device');$('#refresh').onclick=render}
async function devicePage(){const d=await api('/device');content.innerHTML=`<div class="settings-grid">${panel('Device identity',field('Device name',d.name,'device-name')+field('Hostname',d.hostname,'hostname')+field('Model',d.model,'model','text','disabled')+field('Serial / development ID',d.serial,'serial','text','disabled'))}${panel('Platform',`<dl class="facts"><dt>OS version</dt><dd>${esc(d.os_version)}</dd><dt>Kernel</dt><dd>${esc(d.kernel)}</dd><dt>Hardware revision</dt><dd>${esc(d.hardware_revision)}</dd><dt>Backend</dt><dd>${esc(d.backend)}</dd></dl>`)}${panel('Power controls',`<p class="muted">These actions require a confirmation token and are rate limited.</p><div class="button-row">${action('Reboot','power-reboot','outline-btn')}${action('Shut down','power-shutdown','danger-btn')}${action('Factory reset','power-reset','danger-btn')}</div>`,'wide')}</div>`;$('#hostname').onchange=e=>mutate('/network',{hostname:e.target.value},'Hostname saved');$('#power-reboot').onclick=()=>power('reboot','Reboot');$('#power-shutdown').onclick=()=>power('shutdown','Shut down');$('#power-reset').onclick=()=>power('factory-reset','Factory reset')}
async function audioPage(){const a=await api('/audio');content.innerHTML=`<div class="settings-grid">${panel('Output',range('Master volume',a.volume,'volume')+range('Notification volume',a.notification_volume,'notification-volume')+toggle('Startup sound',a.startup_sound,'startup-sound')+`<dl class="facts"><dt>Output</dt><dd class="${a.output_available?'connected':''}">${a.output_available?'Available':'Unavailable'}</dd><dt>Amplifier</dt><dd>${a.amplifier_on?'On':'Off'}</dd></dl>`+action('Play test tone','test-tone','primary-btn'))}${panel('Microphones',range('Microphone gain',a.microphone_gain,'mic-gain')+toggle('Microphone muted',a.microphone_muted,'mic-muted')+toggle('Acoustic echo cancellation',true,'aec',true)+`<p class="muted">Echo cancellation is reported by the future audio adapter and cannot yet be changed.</p>`)}</div>`;bindRange();$('#volume').onchange=e=>mutate('/audio',{volume:+e.target.value},'Volume saved');$('#mic-gain').onchange=e=>mutate('/audio',{microphone_gain:+e.target.value},'Microphone gain saved');$('#mic-muted').onchange=e=>mutate('/audio',{microphone_muted:e.target.checked},'Microphone state saved');$('#test-tone').onclick=()=>post('/audio/test',{},'Test tone playing')}
async function wakePage(){const w=await api('/wake-word');content.innerHTML=`<div class="settings-grid">${panel('Wake-word engine',toggle('Enable wake-word detection',w.enabled,'wake-enabled',true)+select('Active wake word',w.wake_word,'wake-word',['LibreEcho','Computer','Echo','Custom model'])+range('Detection sensitivity',w.sensitivity,'sensitivity')+field('Detection cooldown (ms)',w.cooldown_ms,'cooldown','number','min="250" max="10000" disabled')+action('Simulate detection','wake-test','primary-btn'))}${panel('Local processing',`<div class="privacy-callout">✓ Audio remains on this device</div><dl class="facts"><dt>Model status</dt><dd class="connected">${esc(w.model_status)}</dd><dt>Detections</dt><dd>${w.detected_count}</dd><dt>Estimated CPU cost</dt><dd>${w.cpu_cost_percent}%</dd><dt>Estimated memory cost</dt><dd>${w.memory_cost_mb} MB</dd></dl>`)}</div>`;bindRange();$('#wake-word').onchange=e=>mutate('/wake-word',{wake_word:e.target.value},'Wake word saved');$('#sensitivity').onchange=e=>mutate('/wake-word',{sensitivity:+e.target.value},'Sensitivity saved');$('#wake-test').onclick=()=>post('/wake-word/test',{},'Wake word detected')}
async function ledPage(){const l=await api('/led');const hex='#'+[l.colour.r,l.colour.g,l.colour.b].map(n=>n.toString(16).padStart(2,'0')).join('');content.innerHTML=`<div class="settings-grid">${panel('Light ring',`<label class="field"><span>Current colour</span><input id="led-colour" type="color" value="${hex}"></label>`+range('Brightness',l.brightness,'led-brightness')+`<div class="led-preview" style="--led:${rgb(l.colour)}"><i></i><span>Live preview</span></div>`+action('Run LED test','led-test','primary-btn'))}${panel('Profiles',`<div class="profile-grid">${Object.entries(l.profiles).map(([k,v])=>`<div><i style="background:${v}"></i><span>${k}</span></div>`).join('')}</div><p class="muted">Listening, thinking, error and do-not-disturb profile editing is prepared in the backend interface; device animation semantics require hardware research.</p>`)}${panel('Buttons',select('Short press','Start listening','short-action',['Start listening','Play / pause','Run automation','Disabled'])+select('Long press','Open pairing mode','long-action',['Open pairing mode','Toggle privacy mode','Reboot device'])+toggle('Hardware mute state',false,'hw-mute',true),'wide')}</div>`;bindRange();$('#led-colour').onchange=e=>{const h=e.target.value;mutate('/led',{r:parseInt(h.slice(1,3),16),g:parseInt(h.slice(3,5),16),b:parseInt(h.slice(5,7),16)},'LED colour saved')};$('#led-brightness').onchange=e=>mutate('/led',{brightness:+e.target.value},'LED brightness saved');$('#led-test').onclick=()=>post('/led/test',{},'LED test started')}
async function networkPage(){const n=await api('/network');content.innerHTML=`<div class="settings-grid">${panel('Wireless network',`<div class="status-line"><span class="status-dot ${n.state==='connected'?'ok':''}"></span><div><strong>${esc(n.state)}</strong><small>${esc(n.ssid||'No network')}</small></div><span>${n.signal||0}%</span></div><div id="wifi-results" class="wifi-results"><p class="muted">Scan to discover nearby networks.</p></div><div class="button-row">${action('Scan Wi-Fi','wifi-scan','primary-btn')}${action('Disconnect','wifi-disconnect')}</div>`)}${panel('Addressing',field('Hostname',n.hostname,'net-hostname')+toggle('Use DHCP',n.dhcp,'dhcp',true)+`<dl class="facts"><dt>IP address</dt><dd>${esc(n.ip||'—')}</dd><dt>Gateway</dt><dd>${esc(n.gateway||'—')}</dd><dt>DNS</dt><dd>${esc(n.dns||'—')}</dd><dt>Internet</dt><dd class="${n.internet?'connected':''}">${n.internet?'Reachable':'Unavailable'}</dd></dl>`)}${panel('Local access',toggle('LAN API access',n.api_lan,'api-lan',true)+toggle('SSH',n.ssh,'ssh',true)+`<p class="muted">Loopback binding is the secure default. LAN access and SSH require explicit production authentication configuration.</p>`,'wide')}</div>`;$('#net-hostname').onchange=e=>mutate('/network',{hostname:e.target.value},'Hostname saved');$('#wifi-scan').onclick=async()=>{const box=$('#wifi-results');box.innerHTML='<p class="muted">Scanning…</p>';try{const s=await api('/network/wifi/scan');box.innerHTML=s.networks.map(x=>`<button class="wifi-network" data-ssid="${esc(x.ssid)}" data-security="${x.security}"><span><strong>${esc(x.ssid)}</strong><small>${x.security}</small></span><span>${x.signal}%</span></button>`).join('');$$('.wifi-network').forEach(b=>b.onclick=()=>connectWifi(b.dataset.ssid,b.dataset.security))}catch(e){box.innerHTML=`<p class="error-text">${esc(e.message)}</p>`}};$('#wifi-disconnect').onclick=()=>post('/network/wifi/disconnect',{},'Wi-Fi disconnected')}
async function connectWifi(ssid,security){let password='';if(security!=='open'){password=prompt(`Password for ${ssid}`)||'';if(!password)return}await post('/network/wifi/connect',{ssid,password,security},`Connecting to ${ssid}`)}
async function privacyPage(){const p=await api('/privacy');content.innerHTML=`<div class="settings-grid">${panel('Processing',toggle('Local speech recognition only',p.local_only,'local-only')+toggle('Retain microphone audio',p.audio_retention!=='none','audio-retention')+toggle('Diagnostic telemetry',p.diagnostic_telemetry,'telemetry')+toggle('Crash reports',p.crash_reports,'crash-reports'))}${panel('Retention',select('Log retention',String(p.log_retention_hours)+' hours','retention',['24 hours','168 hours','720 hours'])+`<div class="privacy-callout">No cloud dependency is enabled by default.</div>`+action('Reset privacy settings','privacy-reset','danger-btn'))}</div>`;$$('.toggle-input,select',content).forEach(x=>x.onchange=()=>mutate('/privacy',{local_only:$('#local-only').checked,audio_retention:$('#audio-retention').checked?'24h':'none',diagnostic_telemetry:$('#telemetry').checked,crash_reports:$('#crash-reports').checked},'Privacy settings saved'));$('#privacy-reset').onclick=()=>confirm('Reset privacy settings?')&&toast('Privacy defaults restored')}
async function integrationsPage(){const d=await api('/integrations');content.innerHTML=`<div class="integration-grid">${d.items.map(x=>panel(x.name,`<p class="muted">${x.id==='rest'?'Versioned local device API.':'Optional local integration; no cloud connection required.'}</p>${toggle('Enabled',x.enabled,'int-'+x.id)}<div class="status-line"><span class="status-dot ${x.enabled?'ok':''}"></span><span>${x.enabled?'Enabled':'Not configured'}</span></div>`)).join('')}</div>`;$$('.toggle-input').forEach(x=>x.onchange=()=>mutate('/integrations/'+x.id.slice(4),{enabled:x.checked},'Integration updated'))}
async function systemPage(){const [s,d]=await Promise.all([api('/system'),api('/device')]);content.innerHTML=`<div class="settings-grid">${panel('Software',`<dl class="facts"><dt>OS version</dt><dd>${esc(d.os_version)}</dd><dt>Kernel</dt><dd>${esc(d.kernel)}</dd><dt>Update channel</dt><dd>${esc(s.update_channel)}</dd><dt>Time zone</dt><dd>${esc(s.timezone)}</dd><dt>NTP</dt><dd class="connected">${s.ntp?'Synchronized':'Unavailable'}</dd></dl>`)}${panel('A/B OTA design',`<dl class="facts"><dt>Current slot</dt><dd>${s.ota.current_slot}</dd><dt>Inactive slot</dt><dd>${s.ota.inactive_slot}</dd><dt>State</dt><dd>${s.ota.state}</dd><dt>Rollback</dt><dd>${s.ota.rollback_available?'Available':'Unavailable'}</dd></dl><div class="progress"><i style="width:${s.ota.progress}%"></i></div>${!s.ota.supported?unsupported('Safe partition and boot-control adapters are not implemented. No block-device writes are performed.'):''}`)}${panel('Backup and diagnostics',`<div class="button-row">${action('Backup configuration','backup')}${action('Restore configuration','restore')}${action('Export diagnostics','export-diag','primary-btn')}</div><p class="muted">Restore and local package upload remain placeholders until signed-file validation is implemented.</p>`,'wide')}</div>`;$('#backup').onclick=()=>toast('Backup placeholder — no secret data exported');$('#restore').onclick=()=>toast('Restore is not yet supported',true);$('#export-diag').onclick=()=>post('/diagnostics/export',{},'Redacted diagnostics prepared')}
async function logsPage(){const [l,d]=await Promise.all([api('/logs'),api('/diagnostics')]);content.innerHTML=`${panel('Service logs',`<div class="log-toolbar"><input id="log-filter" placeholder="Filter logs" aria-label="Filter logs">${action('Refresh','log-refresh')}</div><div class="log-viewer" id="log-viewer">${l.entries.length?l.entries.map(x=>`<div data-log="${esc(x.message.toLowerCase())}"><time>${new Date(x.timestamp*1000).toLocaleTimeString()}</time><span class="level ${x.level}">${x.level}</span><span>${esc(x.message)}</span></div>`).join(''):'<p class="muted">No logs available.</p>'}</div><p class="muted">Bounded in-memory buffer: ${l.capacity} entries. Secrets are redacted before logging.</p>`)}<div class="settings-grid diagnostics">${panel('Diagnostic checks',d.checks.map(x=>`<div class="status-line"><span class="status-dot ${x.status==='ok'?'ok':''}"></span><span>${esc(x.name)}</span><strong>${esc(x.status)}</strong></div>`)}${panel('Mock fault injection',state.data.status?.simulated?`<p class="muted">Use <code>tools/mockctl.sh</code> with <code>--dev-controls</code> to inject deterministic faults.</p>${action('Fail next Wi-Fi scan','fail-wifi','danger-btn')}`:unsupported('Fault injection is only available in mock development builds.'))}</div>`;$('#log-filter').oninput=e=>$$('[data-log]').forEach(x=>x.hidden=!x.dataset.log.includes(e.target.value.toLowerCase()));$('#log-refresh').onclick=render;if($('#fail-wifi'))$('#fail-wifi').onclick=()=>post('/dev/mock',{action:'fail-next',value:'wifi-scan'},'Next Wi-Fi scan will fail')}
function aboutPage(){content.innerHTML=`<div class="settings-grid">${panel('LibreEcho',`<img class="about-mark" src="/assets/mark.svg" alt="LibreEcho mark"><p>Open source voice-assistant software built for privacy, repairability and local control.</p><dl class="facts"><dt>Web API</dt><dd>v1</dd><dt>Frontend</dt><dd>Dependency-free HTML, CSS and JavaScript</dd><dt>Daemon</dt><dd>Portable C99</dd><dt>Licence</dt><dd>MIT</dd></dl>`)}${panel('Hardware independence',`<p class="muted">The same frontend API works with both the realistic mock backend and the conservative Linux hardware adapter.</p><div class="privacy-callout">Open. Private. Yours.</div>`)}</div>`}
async function render(){clearTimeout(state.timer);content.innerHTML='<div class="panel loading">Loading device state…</div>';try{if(state.page==='Overview')await overview();else if(state.page==='Device')await devicePage();else if(state.page==='Audio')await audioPage();else if(state.page==='Wake Word')await wakePage();else if(state.page==='LED & Buttons')await ledPage();else if(state.page==='Network')await networkPage();else if(state.page==='Privacy')await privacyPage();else if(state.page==='Integrations')await integrationsPage();else if(state.page==='System')await systemPage();else if(state.page==='Logs')await logsPage();else aboutPage()}catch(e){errorView(e)}if(state.page==='Overview')state.timer=setTimeout(render,5000)}
function showPage(name){state.page=name;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$('#page-title').textContent=name;$('#page-subtitle').textContent=descriptions[name];document.body.classList.remove('nav-open');render()}
items.forEach(([name,icon],i)=>{const b=document.createElement('button');b.className='nav-item'+(i?'':' active');b.dataset.page=name;b.innerHTML=`<svg><use href="#${icon}"></use></svg><span>${name}</span>`;b.onclick=()=>showPage(name);nav.appendChild(b)});
$('#reboot').onclick=()=>power('reboot','Reboot');$('#theme').onclick=()=>document.body.classList.toggle('light');$('#menu').onclick=()=>document.body.classList.toggle('nav-open');
api('/config').then(c=>{state.csrf=c.csrf_token;render()}).catch(errorView);
