'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={page:'Overview',csrf:'',token:sessionStorage.getItem('libreecho-token')||'',username:sessionStorage.getItem('libreecho-username')||'',authMode:'development-disabled',timer:null,data:{},busy:false};
const items=[['Overview','home'],['Device','device'],['Audio','audio'],['Baby Monitor','mic'],['Wake Word','mic'],['LED & Buttons','sun'],['Network','wifi'],['Bluetooth','bluetooth'],['Privacy','shield'],['Integrations','puzzle'],['System','gear'],['Logs','log'],['About','info']];
const descriptions={Overview:'Your LibreEcho at a glance',Device:'Identity, hardware and power controls',Audio:'Playback, microphone and volume controls','Baby Monitor':'Listen to selected microphones locally','Wake Word':'Configure local wake-word detection','LED & Buttons':'Customise light-ring behaviour and controls',Network:'Wi-Fi, addressing and connectivity',Bluetooth:'Scan, pair and manage nearby devices',Privacy:'Local processing and data retention controls',Integrations:'Connect services and home automation',System:'Updates, backup and advanced settings',Logs:'Diagnostics and troubleshooting',About:'Project, licences and version information'};
const nav=$('#nav'),content=$('#content');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(path,opt={}){const headers={'Accept':'application/json',...(state.token?{'Authorization':'Bearer '+state.token}:{}),...(opt.body?{'Content-Type':'application/json','X-LibreEcho-CSRF':state.csrf}:{}),...(opt.headers||{})};const res=await fetch('/api/v1'+path,{...opt,headers});let body;try{body=await res.json()}catch(_){throw new Error('The device returned an unreadable response')}if(!res.ok||!body.ok)throw new Error(body.error?.message||`Request failed (${res.status})`);return body.data}
function toast(message,error=false){const t=$('#toast');t.textContent=message;t.classList.toggle('error',error);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function panel(title,body,extra=''){return `<section class="panel setting-panel ${extra}"><h3>${title}</h3>${body}</section>`}
function field(label,value,id,type='text',extra=''){return `<label class="field"><span>${label}</span><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function range(label,value,id){return `<label class="field range-field"><span>${label}: <output>${value}%</output></span><input id="${id}" type="range" min="0" max="100" value="${value}"></label>`}
function toggle(label,on,id,disabled=false){return `<label class="switch-row"><span>${label}</span><input class="toggle-input" id="${id}" type="checkbox" ${on?'checked':''} ${disabled?'disabled':''}><span class="switch" aria-hidden="true"></span></label>`}
function select(label,value,id,values){return `<label class="field"><span>${label}</span><select id="${id}">${values.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`}
function action(label,id,kind='secondary-btn'){return `<button class="${kind}" id="${id}">${label}</button>`}
function linkAction(label,href,kind='secondary-btn'){return `<a class="${kind} action-link" href="${href}">${label}</a>`}
function saveButton(id){return `<button class="save-btn save-changes" id="${id}" disabled>Save changes</button>`}
function unsupported(msg){return `<div class="notice unsupported"><strong>Not supported</strong><span>${esc(msg)}</span></div>`}
function errorView(e){content.innerHTML=panel('Unable to load this section',`<div class="empty-state"><p>${esc(e.message)}</p>${action('Try again','retry','primary-btn')}</div>`);$('#retry').onclick=()=>render()}
function storageDisplay(value){const text=String(value??''),match=text.match(/^(null|\d+) \/ (null|\d+) MB$/);if(!match)return text==='undefined'||text==='null'||text==='NaN'?'Unavailable':text;const used=match[1]==='null'?null:Number(match[1]),total=match[2]==='null'?null:Number(match[2]);if(total===null||total<=0)return'Unavailable';return used===null?`${total} MB capacity · usage unavailable`:`${used} / ${total} MB`}
function storageValue(s){const total=Number(s?.storage_total_mb);if(!Number.isFinite(total)||total<=0)return'Unavailable';if(s.storage_available&&Number.isFinite(Number(s.storage_used_mb)))return`${Number(s.storage_used_mb)} / ${total} MB`;return`${total} MB capacity · usage unavailable`}
function metric(icon,label,value,percent,connected=false,powerLed=false){if(label==='Storage')value=storageDisplay(value);const numericPercent=Number(percent),hasPercent=Number.isFinite(numericPercent);return `<div class="metric ${powerLed?'binary-metric':''}"><svg><use href="#${icon}"></use></svg><span>${label}</span><span class="value ${connected?'connected':''}">${esc(value)}</span>${powerLed?`<span class="power-led ${connected?'on':'off'}" role="img" aria-label="${connected?'Available':'Unavailable'}"></span>`:hasPercent?`<progress class="bar" max="100" value="${Math.max(0,Math.min(100,numericPercent))}" aria-label="${esc(label)}: ${esc(value)}"></progress>`:''}</div>`}
function cpuDashboard(s){const cores=Array.isArray(s.cpus)?s.cpus:(Array.isArray(s.cpus?.cores)?s.cpus.cores:[]);return `<section class="panel cpu-panel" id="cpu-dashboard"><div class="cpu-heading"><h3>CPU cores</h3><span>${cores.filter(c=>c.online).length}/${cores.length} online</span></div><div class="cpu-core-grid">${cores.map(c=>`<article class="cpu-core ${c.online?'online':'offline'}"><div><strong>CPU${esc(c.id)}</strong><small>${c.online?'Up':'Down'} · ${c.frequency_khz?Math.round(c.frequency_khz/1000)+' MHz':'—'}</small></div><b>${c.online?Number(c.utilization_percent??c.utilization??0)+'%':'—'}</b><progress class="bar" max="100" value="${c.online?Math.max(0,Math.min(100,Number(c.utilization_percent??c.utilization??0))):0}" aria-label="CPU${c.id} utilization"></progress></article>`).join('')}</div></section>`}
function playbackSource(source){return ({airplay2:'AirPlay 2',bluetooth:'Bluetooth',media:'Media',system:'System',announcement:'Announcement',alarm:'Alarm'})[source]||source||'LibreEcho'}
function nowPlaying(p={},l={}){const active=p.state&&p.state!=='idle',metadata=p.metadata||{},levels=Array.isArray(l.visualizer_levels)&&l.visualizer_levels.length===12?l.visualizer_levels:Array(12).fill(0);let title='Nothing playing',detail='Your audio sources will appear here',source='Idle';if(p.state==='playing'){title=metadata.title||`${playbackSource(p.source)} audio`;detail=[metadata.artist,metadata.album].filter(Boolean).join(' · ')||'Playing now';source=playbackSource(p.source)}else if(p.state==='announcing'){title='Announcement in progress';detail='Voice and notification audio has priority';source='Announcement'}else if(p.state==='alarm'){title='Alarm active';detail='Alarm audio has priority';source='Alarm'}else if(p.state==='system'){title='System audio';detail='LibreEcho is playing a system sound';source='System'}return `<section class="panel now-playing ${active?'active':'idle'}" id="now-playing"><div class="now-playing-mark" aria-hidden="true"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="36"></circle><circle cx="50" cy="50" r="8"></circle></svg></div><div class="now-playing-copy"><span class="source-pill">${esc(source)}</span><h3>${esc(title)}</h3><p>${esc(detail)}</p></div><div class="spectrum-mini" aria-label="${l.visualizer_active?'Live 12-band music spectrum':'Audio spectrum inactive'}">${levels.map((v,i)=>`<i style="--level:${Math.max(4,Math.min(100,Math.round(Number(v)||0)))}%;--band:${i}"></i>`).join('')}</div><div class="now-playing-state"><span class="status-dot ${active?'ok':''}"></span>${esc(p.state||'idle')}</div></section>`}
function uptime(s){s=Math.max(0,Number(s)||0);const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return `${d?d+'d ':''}${h}h ${m}m`}
function logTime(t,boot){const seconds=Number(t),relative=Number(boot);if(relative>0)return `Boot +${relative}s`;return seconds>=1577836800?new Date(seconds*1000).toLocaleTimeString():'Clock unset'}
function rgb(c){return `rgb(${c.r}, ${c.g}, ${c.b})`}
function networkLabel(n){return n.ssid?`${n.state} · ${n.ssid}`:n.state}
function bindRange(){ $$('.range-field input').forEach(el=>el.oninput=()=>el.parentElement.querySelector('output').textContent=el.value+'%') }
function bindDirty(ids,button){const b=$(button);ids.map(id=>$(id)).filter(Boolean).forEach(el=>el.addEventListener('input',()=>b.disabled=false));}
function setBusy(b){state.busy=b;$$('button,input,select',content).forEach(x=>x.disabled=b)}
async function mutate(path,data,message,headers={}){if(state.busy)return;setBusy(true);try{await api(path,{method:'PUT',body:JSON.stringify(data),headers});toast(message);await render()}catch(e){toast(e.message,true);await render()}finally{setBusy(false)}}
async function post(path,data={},message='Action accepted',headers={}){if(state.busy)return;setBusy(true);try{const r=await api(path,{method:'POST',body:JSON.stringify(data),headers});toast(message);await render();return r}catch(e){toast(e.message,true);await render()}finally{setBusy(false)}}
function power(path,name){if(!confirm(`${name} this LibreEcho device?`))return;post(`/system/${path}`,{},`${name} requested`,{'X-LibreEcho-Confirm':'confirm-device-action'})}
async function overview(){const [s,n,a,l,d,p]=await Promise.all([api('/status'),api('/network'),api('/audio').catch(e=>({unsupported:e.message})),api('/led').catch(e=>({unsupported:e.message})),api('/device'),api('/playback').catch(()=>({state:'idle',source:null,metadata:{available:false}}))]);state.data.status=s;$('#backend-badge').textContent=s.backend+(s.simulated?' · simulated':'');$('#backend-badge').className='backend-badge '+s.backend;$('#device-online').innerHTML=`<span></span>${esc(s.device_state)}`;$('#sidebar-uptime').textContent='Uptime: '+uptime(s.uptime_seconds);$('#sidebar-version').textContent=d.os_version;content.innerHTML=`<div class="grid-top"><div class="panel hero"><div class="sim-label" id="hero-device-label">${esc(d.hostname||d.name||'LibreEcho')}</div><h2>LibreEcho</h2><p>Open source voice assistant<br>built for privacy and freedom.</p><img class="device-img" src="/assets/device.png" alt="Amazon Echo device"><div class="hero-actions">${action('Device details','device-details','primary-btn')}${linkAction('API','/api/v1')}${linkAction('Swagger','/swagger.html')}</div></div><div class="panel status-panel"><h3>System Status</h3>${metric('device','CPU Load',s.cpu_percent+'%',s.cpu_percent)}${metric('device','Memory',`${s.memory_used_mb} / ${s.memory_total_mb} MB`,s.memory_percent)}${metric('device','Storage',storageValue(s),s.storage_available?s.storage_percent:null)}${metric('sun','Temperature',s.temperature_c+' °C',s.temperature_c)}${metric('wifi','Wi-Fi',networkLabel(n),n.signal,n.state==='connected',true)}${metric('info','Internet',n.internet?'Reachable':'Unavailable',0,n.internet,true)}</div></div>${nowPlaying(p,l)}${cpuDashboard(s)}<div class="cards">${items.slice(2,10).map(([name,icon],i)=>`<button class="panel shortcut" data-page="${name}"><svg class="${['green','purple','blue','sky','green','orange','grey','orange'][i]}"><use href="#${icon}"></use></svg><span><strong>${name}</strong><small>${descriptions[name]}</small></span><span class="arrow">›</span></button>`).join('')}</div><div class="panel community"><img src="/assets/mark.svg" alt="" class="community-mark"><div><h3>Open Source. Community Driven.</h3><p>Configuration stays on your device. ${s.simulated?'This development session uses deterministic mock-capable hardware state.':'Values shown come from the Linux backend.'}</p></div></div>`;$$('[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('#device-details').onclick=()=>showPage('Device')}
function updateOverviewMetric(label,value,percent,connected){const row=$$('.status-panel .metric').find(x=>x.querySelector('span')?.textContent===label);if(!row)return;if(label==='Storage')value=storageDisplay(value);const output=row.querySelector('.value');output.textContent=value;if(connected!==undefined)output.classList.toggle('connected',connected);const bar=row.querySelector('progress');if(bar)bar.value=Math.max(0,Math.min(100,percent));const led=row.querySelector('.power-led');if(led){led.classList.toggle('on',!!connected);led.classList.toggle('off',!connected);led.setAttribute('aria-label',connected?'Available':'Unavailable')}}
async function refreshOverview(){if(state.page!=='Overview')return;let delay=5000;try{const [s,n,d,p,l]=await Promise.all([api('/status'),api('/network'),api('/device'),api('/playback'),api('/led').catch(()=>({}))]);if(state.page!=='Overview')return;state.data.status=s;$('#backend-badge').textContent=s.backend+(s.simulated?' · simulated':'');$('#backend-badge').className='backend-badge '+s.backend;$('#device-online').innerHTML=`<span></span>${esc(s.device_state)}`;$('#sidebar-uptime').textContent='Uptime: '+uptime(s.uptime_seconds);$('#sidebar-version').textContent=d.os_version;const deviceLabel=$('#hero-device-label');if(deviceLabel)deviceLabel.textContent=d.hostname||d.name||'LibreEcho';updateOverviewMetric('CPU Load',s.cpu_percent+'%',s.cpu_percent);updateOverviewMetric('Memory',`${s.memory_used_mb} / ${s.memory_total_mb} MB`,s.memory_percent);updateOverviewMetric('Storage',storageValue(s),s.storage_available?s.storage_percent:null);updateOverviewMetric('Temperature',s.temperature_c+' °C',s.temperature_c);updateOverviewMetric('Wi-Fi',networkLabel(n),0,n.state==='connected');updateOverviewMetric('Internet',n.internet?'Reachable':'Unavailable',0,n.internet);const playing=$('#now-playing');if(playing)playing.outerHTML=nowPlaying(p,l);const cpu=$('#cpu-dashboard');if(cpu)cpu.outerHTML=cpuDashboard(s);if(p.state!=='idle'||l.visualizer_active)delay=1000}catch(_){/* Preserve the last good telemetry when a background refresh fails. */}finally{if(state.page==='Overview')state.timer=setTimeout(refreshOverview,delay)}}
async function devicePage(){const d=await api('/device');content.innerHTML=`<div class="settings-grid">${panel('Device identity',field('Device name',d.name,'device-name','text','disabled')+field('Hostname',d.hostname,'hostname')+field('Model',d.model,'model','text','disabled')+field('Serial / development ID',d.serial,'serial','text','disabled')+saveButton('save-device'))}${panel('Platform',`<dl class="facts"><dt>OS version</dt><dd>${esc(d.os_version)}</dd><dt>Kernel</dt><dd>${esc(d.kernel)}</dd><dt>Hardware revision</dt><dd>${esc(d.hardware_revision)}</dd><dt>Backend</dt><dd>${esc(d.backend)}</dd></dl>`)}${panel('Power controls',`<p class="muted">These actions require a confirmation token and are rate limited.</p><div class="button-row">${action('Reboot','power-reboot','outline-btn')}${action('Shut down','power-shutdown','danger-btn')}${action('Factory reset','power-reset','danger-btn')}</div>`,'wide')}</div>`;bindDirty(['#hostname'],'#save-device');$('#save-device').onclick=()=>mutate('/network',{hostname:$('#hostname').value},'Device changes saved');$('#power-reboot').onclick=()=>power('reboot','Reboot');$('#power-shutdown').onclick=()=>power('shutdown','Shut down');$('#power-reset').onclick=()=>power('factory-reset','Factory reset')}
async function audioPage(){const a=await api('/audio');content.innerHTML=`<div class="settings-grid">${panel('Output',range('Master volume',a.volume,'volume')+range('Notification volume',a.notification_volume,'notification-volume').replace('value="'+a.notification_volume+'"','value="'+a.notification_volume+'" disabled')+toggle('Startup sound',a.startup_sound,'startup-sound',true)+`<dl class="facts"><dt>Output</dt><dd class="${a.output_available?'connected':''}">${a.output_available?'Available':'Unavailable'}</dd><dt>Amplifier</dt><dd>${a.amplifier_on?'On':'Off'}</dd></dl><div class="button-row">${saveButton('save-output')}${action('Play test tone','test-tone')}</div>`)}${panel('Microphones',range('Microphone gain',a.microphone_gain,'mic-gain')+toggle('Microphone muted',a.microphone_muted,'mic-muted')+toggle('Acoustic echo cancellation',true,'aec',true)+`<p class="muted">Echo cancellation is reported by the future audio adapter and cannot yet be changed.</p>`+saveButton('save-microphones'))}</div>`;bindRange();bindDirty(['#volume'],'#save-output');bindDirty(['#mic-gain','#mic-muted'],'#save-microphones');$('#save-output').onclick=()=>mutate('/audio',{volume:+$('#volume').value},'Output changes saved');$('#save-microphones').onclick=()=>mutate('/audio',{microphone_gain:+$('#mic-gain').value,microphone_muted:$('#mic-muted').checked},'Microphone changes saved');$('#test-tone').onclick=()=>post('/audio/test',{},'Test tone playing')}
const babyStream={controller:null,context:null,gain:null,nextTime:0};
function stopBabyStream(){if(babyStream.controller)babyStream.controller.abort();babyStream.controller=null;if(babyStream.context){babyStream.context.close().catch(()=>{});babyStream.context=null}babyStream.gain=null;babyStream.nextTime=0;const status=$('#baby-status');if(status)status.textContent='Stopped'}
async function babyMonitorPage(){
  const d=await api('/baby-monitor');
  if(!d.sources.length){
    content.innerHTML='<div class="settings-grid">'+panel('Baby monitor',unsupported('No Echo microphone array is currently available.'))+
      panel('Privacy','<p class="muted">Audio is streamed directly from this browser and is not recorded by LibreEcho.</p>')+'</div>';
    return;
  }
  const options=d.sources.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+' · card '+x.card+', device '+x.device+'</option>').join('');
  const first=d.sources[0];
  const microphoneOptions=source=> (source.microphones||[{channel:0,name:'Microphone 1'}])
    .map(x=>'<option value="'+x.channel+'">'+esc(x.name)+'</option>').join('');
  content.innerHTML='<div class="settings-grid">'+
    panel('Microphone source','<label class="field"><span>Capture endpoint</span><select id="baby-source">'+options+
      '</select></label><label class="field"><span>Microphone</span><select id="baby-channel">'+microphoneOptions(first)+
      '</select></label><p class="muted">The Echo array exposes nine packed 24-bit microphone channels at 16 kHz. Select one channel to monitor locally.</p>'+
      (d.simulated?'<div class="notice unsupported"><strong>Preview only</strong><span>The mock backend exposes a source list but cannot produce live microphone audio.</span></div>':'')+
      '</div>')+
    panel('Playback',range('Browser playback volume',35,'baby-volume')+
      '<div class="status-line"><span class="status-dot" id="baby-dot"></span><span id="baby-status" aria-live="polite">Stopped</span></div>'+
      '<div class="button-row">'+action('Start listening','baby-start','primary-btn')+action('Stop','baby-stop')+'</div>'+
      '<p class="muted">Listening starts only when you press the button. Closing this page stops capture.</p>')+
    '</div>';
  bindRange();
  const sourceSelect=$('#baby-source');
  const channelSelect=$('#baby-channel');
  const updateChannels=()=>{
    const source=d.sources.find(x=>x.id===sourceSelect.value)||first;
    channelSelect.innerHTML=microphoneOptions(source);
  };
  sourceSelect.onchange=updateChannels;
  $('#baby-volume').oninput=()=>{
    const value=Number($('#baby-volume').value)/100;
    $('#baby-volume').parentElement.querySelector('output').textContent=$('#baby-volume').value+'%';
    if(babyStream.gain)babyStream.gain.gain.value=value;
  };
  $('#baby-start').onclick=async()=>{
    stopBabyStream();
    if(d.simulated){toast('Live microphone streaming is unavailable in the mock backend',true);return}
    const source=d.sources.find(x=>x.id===sourceSelect.value)||first;
    const channel=Number(channelSelect.value)||0;
    const channels=Number(source.channels)||1;
    const bits=Number(source.bits)||16;
    const rate=Number(source.rate)||16000;
    const bytesPerSample=bits===24?3:2;
    const frameBytes=channels*bytesPerSample;
    const context=new(window.AudioContext||window.webkitAudioContext)();
    babyStream.context=context;
    babyStream.controller=new AbortController();
    babyStream.nextTime=context.currentTime+0.05;
    const gain=context.createGain();
    gain.gain.value=Number($('#baby-volume').value)/100;
    gain.connect(context.destination);
    babyStream.gain=gain;
    $('#baby-status').textContent='Connecting…';
    $('#baby-dot').classList.add('ok');
    try{
      await context.resume();
      const response=await fetch('/api/v1/baby-monitor/stream?source='+encodeURIComponent(source.id)+'&channel='+channel,{
        headers:{Accept:'application/octet-stream',...(state.token?{Authorization:'Bearer '+state.token}:{})},
        signal:babyStream.controller.signal
      });
      if(!response.ok)throw new Error('Microphone stream failed ('+response.status+')');
      $('#baby-status').textContent='Listening';
      const reader=response.body.getReader();
      let carry=new Uint8Array(0);
      while(true){
        const chunk=await reader.read();
        if(chunk.done)break;
        const bytes=new Uint8Array(carry.length+chunk.value.length);
        bytes.set(carry);
        bytes.set(chunk.value,carry.length);
        const frames=Math.floor(bytes.length/frameBytes);
        const used=frames*frameBytes;
        if(!frames){carry=bytes;continue}
        carry=bytes.slice(used);
        const audio=context.createBuffer(1,frames,rate);
        const samples=audio.getChannelData(0);
        for(let i=0;i<frames;i++){
          const offset=i*frameBytes+channel*bytesPerSample;
          let value;
          if(bits===24){
            value=bytes[offset]|(bytes[offset+1]<<8)|(bytes[offset+2]<<16);
            if(value&0x800000)value|=-16777216;
            samples[i]=value/8388608;
          }else{
            value=bytes[offset]|(bytes[offset+1]<<8);
            if(value&0x8000)value|=-65536;
            samples[i]=value/32768;
          }
        }
        const node=context.createBufferSource();
        node.buffer=audio;
        node.connect(gain);
        const start=Math.max(babyStream.nextTime,context.currentTime+0.02);
        node.start(start);
        babyStream.nextTime=start+audio.duration;
      }
    }catch(e){
      if(e.name!=='AbortError'){console.error(e);toast(e.message,true)}
      stopBabyStream();
    }
  };
  $('#baby-stop').onclick=stopBabyStream;
}
async function wakePage(){let w;try{w=await api('/wake-word')}catch(e){if(/not available|not supported/i.test(e.message)){content.innerHTML=`<div class="settings-grid">${panel('Wake-word engine',unsupported('The wake-word adapter is not installed in this image. No microphone processing is running.'))}</div>`;return}throw e}content.innerHTML=`<div class="settings-grid">${panel('Wake-word engine',toggle('Enable wake-word detection',w.enabled,'wake-enabled',true)+select('Active wake word',w.wake_word,'wake-word',['LibreEcho','Computer','Echo','Custom model'])+range('Detection sensitivity',w.sensitivity,'sensitivity')+field('Detection cooldown (ms)',w.cooldown_ms,'cooldown','number','min="250" max="10000" disabled')+`<div class="button-row">${saveButton('save-wake')}${action('Simulate detection','wake-test')}</div>`)}${panel('Local processing',`<div class="privacy-callout">✓ Audio remains on this device</div><dl class="facts"><dt>Model status</dt><dd class="connected">${esc(w.model_status)}</dd><dt>Detections</dt><dd>${w.detected_count}</dd><dt>Estimated CPU cost</dt><dd>${w.cpu_cost_percent}%</dd><dt>Estimated memory cost</dt><dd>${w.memory_cost_mb} MB</dd></dl>`)}</div>`;bindRange();bindDirty(['#wake-word','#sensitivity'],'#save-wake');$('#save-wake').onclick=()=>mutate('/wake-word',{wake_word:$('#wake-word').value,sensitivity:+$('#sensitivity').value},'Wake-word changes saved');$('#wake-test').onclick=()=>post('/wake-word/test',{},'Wake word detected')}
function ledRing(l){const physical=Array.isArray(l.pixels)&&l.pixels.length===12,colours=physical?l.pixels:Array.from({length:24},()=>l.colour),count=colours.length,opacity=physical?1:Math.max(0,Math.min(1,Number(l.brightness??0)/100));const dots=colours.map((colour,i)=>{const angle=(i/count)*Math.PI*2-Math.PI/2,x=50+38*Math.cos(angle),y=50+38*Math.sin(angle);return `<circle class="led-pixel" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="${physical?'6.4':'5.5'}" fill="${rgb(colour)}" opacity="${opacity.toFixed(2)}"></circle>`}).join('');const label=l.pattern_active?`Pattern · ${esc(l.pattern||'pattern')}`:l.visualizer_active?`Music visualizer · ${esc(l.visualizer_mood||'balanced')}`:l.animation_active?`Animating · ${esc(l.animation_profile||'profile')}`:'Steady',moving=l.animation_active||l.pattern_active;return `<div class="led-ring-view${moving?' animating':''}${l.visualizer_active?' reactive':''}" role="img" aria-label="${esc(label)} LED ring"><svg viewBox="0 0 100 100" aria-hidden="true"><circle class="led-ring-track" cx="50" cy="50" r="38"></circle>${dots}<circle class="led-ring-centre" cx="50" cy="50" r="24"></circle></svg><span>${esc(label)}</span></div>`}
function updateLedVisual(l){const ring=$('.led-ring-view');if(ring)ring.outerHTML=ledRing(l);const preview=$('.led-preview');if(preview)preview.style.setProperty('--led',rgb(l.colour))}
async function refreshLed(){if(state.page!=='LED & Buttons')return;let delay=1000;try{const l=await api('/led');updateLedVisual(l);if(l.visualizer_active)delay=200}catch(_){/* Preserve the last good LED state during a transient adapter failure. */}finally{if(state.page==='LED & Buttons')state.timer=setTimeout(refreshLed,delay)}}
async function ledPage(){const [l,b]=await Promise.all([api('/led'),api('/buttons')]);const hex='#'+[l.colour.r,l.colour.g,l.colour.b].map(n=>n.toString(16).padStart(2,'0')).join('');content.innerHTML=`<div class="settings-grid">${panel('Light ring',`<label class="field"><span>Current colour</span><input id="led-colour" type="color" value="${hex}"></label>`+range('Brightness',l.brightness,'led-brightness')+toggle('Music visualizer',l.visualizer_enabled!==false,'led-visualizer')+`<p class="muted">Show reactive equalizer animations on the ring while music is playing.</p>`+ledRing(l)+`<div class="led-preview" style="--led:${rgb(l.colour)}"><i></i><span>Live preview</span></div><div class="button-row">${saveButton('save-led')}${action('Run LED test','led-test')}</div>`)}${panel('Profiles',`<div class="profile-grid">${Object.entries(l.profiles).map(([k,v])=>`<div><i style="background:${v}"></i><span>${k}</span></div>`).join('')}</div><p class="muted">Listening, thinking, error and do-not-disturb profile editing is prepared in the backend interface; device animation semantics require hardware research.</p>`)}${panel('Buttons',select('Short press',b.short_press,'short-action',['Start listening','Play / pause','Run automation','Disabled'])+select('Long press',b.long_press,'long-action',['Open pairing mode','Toggle privacy mode','Reboot device'])+toggle('Hardware mute state',b.hardware_mute,'hw-mute',true)+saveButton('save-buttons'),'wide')}</div>`;bindRange();bindDirty(['#led-colour','#led-brightness','#led-visualizer'],'#save-led');bindDirty(['#short-action','#long-action'],'#save-buttons');$('#save-led').onclick=()=>{const h=$('#led-colour').value;mutate('/led',{r:parseInt(h.slice(1,3),16),g:parseInt(h.slice(3,5),16),b:parseInt(h.slice(5,7),16),brightness:+$('#led-brightness').value,visualizer_enabled:$('#led-visualizer').checked},'LED changes saved')};$('#save-buttons').onclick=()=>mutate('/buttons',{short_press:$('#short-action').value,long_press:$('#long-action').value},'Button changes saved');$('#led-test').onclick=()=>post('/led/test',{},'LED test started');state.timer=setTimeout(refreshLed,1000)}
async function networkPage(){const n=await api('/network'),lanEffective=n.api_lan_effective??n.api_lan,lanForced=!!n.api_lan_forced;content.innerHTML=`<div class="settings-grid">${panel('Wireless network',`<div class="status-line"><span class="status-dot ${n.state==='connected'?'ok':''}"></span><div><strong>${esc(n.state)}</strong><small>${esc(n.ssid||'No network')}</small></div><span>${n.signal||0}%</span></div><div id="wifi-results" class="wifi-results"><p class="muted">Scan to discover nearby networks.</p></div><div class="button-row">${action('Scan Wi-Fi','wifi-scan','primary-btn')}${action('Disconnect','wifi-disconnect')}</div>`)}${panel('Addressing',field('Hostname',n.hostname,'net-hostname')+toggle('Use DHCP',n.dhcp,'dhcp',true)+`<dl class="facts"><dt>IP address</dt><dd>${esc(n.ip||'—')}</dd><dt>Gateway</dt><dd>${esc(n.gateway||'—')}</dd><dt>DNS</dt><dd>${esc(n.dns||'—')}</dd><dt>Internet</dt><dd class="${n.internet?'connected':''}">${n.internet?'Reachable':'Unavailable'}</dd></dl>`+saveButton('save-network'))}${panel('Local access',toggle('LAN API access',lanEffective,'api-lan',lanForced)+toggle('SSH',n.ssh,'ssh')+`<p class="muted">${lanForced?'LAN API access is forced by the development image binding. Authentication is intentionally disabled for this development build.':'Enabling LAN access exposes the API beyond loopback. Configure authentication before using this on an untrusted network.'}</p>`+saveButton('save-access'),'wide')}</div>`;bindDirty(['#net-hostname'],'#save-network');bindDirty(['#api-lan','#ssh'],'#save-access');$('#save-network').onclick=()=>mutate('/network',{hostname:$('#net-hostname').value},'Network changes saved');$('#save-access').onclick=()=>mutate('/network',{api_lan:$('#api-lan').checked,ssh:$('#ssh').checked},'Local access changes saved');$('#wifi-scan').onclick=async()=>{const box=$('#wifi-results');box.innerHTML='<p class="muted">Scanning…</p>';try{const s=await api('/network/wifi/scan');box.innerHTML=s.networks.length?s.networks.map(x=>`<button class="wifi-network" data-ssid="${esc(x.ssid)}" data-security="${esc(x.security)}"><span><strong>${esc(x.ssid)}</strong><small>${esc(x.security)}</small></span><span>${x.signal}%</span></button>`).join(''):'<p class="muted">No networks found.</p>';$$('.wifi-network').forEach(b=>b.onclick=()=>connectWifi(b.dataset.ssid,b.dataset.security))}catch(e){box.innerHTML=unsupported(e.message)}};$('#wifi-disconnect').onclick=()=>post('/network/wifi/disconnect',{},'Wi-Fi disconnected')}
async function connectWifi(ssid,security){let password='';if(security!=='open'){password=prompt(`Password for ${ssid}`)||'';if(!password)return}await post('/network/wifi/connect',{ssid,password,security},`Connecting to ${ssid}`)}
async function privacyPage(){const p=await api('/privacy');content.innerHTML=`<div class="settings-grid">${panel('Processing',toggle('Local speech recognition only',p.local_only,'local-only')+toggle('Retain microphone audio',p.audio_retention!=='none','audio-retention')+toggle('Diagnostic telemetry',p.diagnostic_telemetry,'telemetry')+toggle('Crash reports',p.crash_reports,'crash-reports')+saveButton('save-privacy'))}${panel('Retention',select('Log retention',String(p.log_retention_hours)+' hours','retention',['24 hours','168 hours','720 hours'])+`<div class="privacy-callout">No cloud dependency is enabled by default.</div><div class="button-row">${saveButton('save-retention')}${action('Reset privacy settings','privacy-reset','danger-btn')}</div>`)}</div>`;bindDirty(['#local-only','#audio-retention','#telemetry','#crash-reports'],'#save-privacy');bindDirty(['#retention'],'#save-retention');$('#save-privacy').onclick=()=>mutate('/privacy',{local_only:$('#local-only').checked,audio_retention:$('#audio-retention').checked?'24h':'none',diagnostic_telemetry:$('#telemetry').checked,crash_reports:$('#crash-reports').checked},'Privacy changes saved');$('#save-retention').onclick=()=>mutate('/privacy',{log_retention_hours:parseInt($('#retention').value,10)},'Retention changes saved');$('#privacy-reset').onclick=()=>confirm('Reset privacy settings?')&&toast('Privacy defaults restored')}
async function integrationsPage(){const d=await api('/integrations');content.innerHTML=`<div class="integration-grid">${d.items.map(x=>panel(x.name,`<p class="muted">${x.id==='rest'?'Versioned local device API.':'Optional local integration; no cloud connection required.'}</p>${toggle('Enabled',x.enabled,'int-'+x.id)}<div class="status-line"><span class="status-dot ${x.enabled?'ok':''}"></span><span>${x.enabled?'Enabled':'Not configured'}</span></div>${saveButton('save-int-'+x.id)}`)).join('')}</div>`;d.items.forEach(x=>{bindDirty(['#int-'+x.id],'#save-int-'+x.id);$('#save-int-'+x.id).onclick=()=>mutate('/integrations/'+x.id,{enabled:$('#int-'+x.id).checked},x.name+' changes saved')})}
async function systemPage(){const [s,d]=await Promise.all([api('/system'),api('/device')]);content.innerHTML=`<div class="settings-grid">${panel('Software',`<dl class="facts"><dt>OS version</dt><dd>${esc(d.os_version)}</dd><dt>Kernel</dt><dd>${esc(d.kernel)}</dd><dt>Update channel</dt><dd>${esc(s.update_channel)}</dd><dt>Time zone</dt><dd>${esc(s.timezone)}</dd><dt>NTP</dt><dd class="${s.ntp?'connected':''}">${s.ntp?'Synchronized':'Unavailable'}</dd><dt>Clock</dt><dd class="${s.clock_valid?'connected':''}">${s.clock_valid?'Valid':`Unset (${esc(s.clock_source||'unknown')})`}</dd></dl>`)}${panel('A/B OTA design',`<dl class="facts"><dt>Current slot</dt><dd>${s.ota.current_slot}</dd><dt>Inactive slot</dt><dd>${s.ota.inactive_slot}</dd><dt>State</dt><dd>${s.ota.state}</dd><dt>Rollback</dt><dd>${s.ota.rollback_available?'Available':'Unavailable'}</dd></dl><progress class="progress" max="100" value="${s.ota.progress}" aria-label="OTA update progress"></progress>${!s.ota.supported?unsupported('Safe partition and boot-control adapters are not implemented. No block-device writes are performed.'):''}`)}${panel('Configuration and diagnostics',`<input id="restore-file" type="file" accept="application/json,.json" hidden><div class="button-row">${action('Download configuration','backup','primary-btn')}${action('Restore configuration','restore')}${action('Export diagnostics','export-diag')}</div><p class="muted">Configuration exports are versioned JSON and exclude Wi-Fi passwords, authentication tokens, logs and live telemetry. Restore validates the complete file before applying it.</p>`,'wide')}</div>`;$('#backup').onclick=async()=>{try{const config=await api('/config/export'),blob=new Blob([JSON.stringify(config,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='libreecho-config.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(config.partial?'Partial configuration downloaded; unsupported fields were omitted':'Configuration downloaded')}catch(e){toast(e.message,true)}};$('#restore').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const config=JSON.parse(await file.text());if(!confirm('Restore this configuration? Current settings will be replaced.'))return;await post('/config/import',config,'Configuration restored');showPage('System')}catch(error){toast(error.message||'Invalid configuration file',true)}finally{e.target.value=''}};$('#export-diag').onclick=()=>post('/diagnostics/export',{},'Redacted diagnostics prepared')}
async function logsPage(){const [l,d]=await Promise.all([api('/logs'),api('/diagnostics')]);const clock=l.entries.some(x=>Number(x.timestamp)<1577836800)?'Device clock unset; relative boot time is shown where available':'Device clock available';content.innerHTML=`${panel('Service logs',`<div class="log-toolbar"><input id="log-filter" placeholder="Filter logs" aria-label="Filter logs">${action('Refresh','log-refresh')}</div><div class="log-viewer" id="log-viewer">${l.entries.length?l.entries.map(x=>`<div data-log="${esc(x.message.toLowerCase())}"><time>${logTime(x.timestamp,x.boot_seconds)}</time><span class="level ${x.level}">${x.level}</span><span>${esc(x.message)}</span></div>`).join(''):'<p class="muted">No logs available.</p>'}</div><p class="muted">Source: ${esc(l.source||'web-memory')}; bounded to ${l.capacity} entries. ${clock}. Relative time is from boot; secrets are redacted before logging.</p>`)}<div class="settings-grid diagnostics">${panel('Diagnostic checks',d.checks.map(x=>`<div class="status-line"><span class="status-dot ${x.status==='ok'?'ok':''}"></span><span>${esc(x.name)}</span><strong>${esc(x.status)}</strong></div>`).join(''))}${panel('Mock fault injection',state.data.status?.simulated?`<p class="muted">Use <code>tools/mockctl.sh</code> with <code>--dev-controls</code> to inject deterministic faults.</p>${action('Fail next Wi-Fi scan','fail-wifi','danger-btn')}`:unsupported('Fault injection is only available in mock development builds.'))}</div>`;$('#log-filter').oninput=e=>$$('[data-log]').forEach(x=>x.hidden=!x.dataset.log.includes(e.target.value.toLowerCase()));$('#log-refresh').onclick=render;if($('#fail-wifi'))$('#fail-wifi').onclick=()=>post('/dev/mock',{action:'fail-next',value:'wifi-scan'},'Next Wi-Fi scan will fail')}
function aboutPage(){content.innerHTML=`<div class="settings-grid">${panel('LibreEcho',`<img class="about-mark" src="/assets/mark.svg" alt="LibreEcho mark"><p>Open source voice-assistant software built for privacy, repairability and local control.</p><dl class="facts"><dt>Web API</dt><dd>v1</dd><dt>Frontend</dt><dd>Dependency-free HTML, CSS and JavaScript</dd><dt>Daemon</dt><dd>Portable C99</dd><dt>Licence</dt><dd>MIT</dd></dl>`)}${panel('Hardware independence',`<p class="muted">The same frontend API works with both the realistic mock backend and the conservative Linux hardware adapter.</p><div class="privacy-callout">Open. Private. Yours.</div>`)}</div>`}
async function render(){clearTimeout(state.timer);content.innerHTML='<div class="panel loading">Loading device state…</div>';try{if(state.page==='Overview')await overview();else if(state.page==='Device')await devicePage();else if(state.page==='Audio')await audioPage();else if(state.page==='Baby Monitor')await babyMonitorPage();else if(state.page==='Wake Word')await wakePage();else if(state.page==='LED & Buttons')await ledPage();else if(state.page==='Network')await networkPage();else if(state.page==='Bluetooth')await bluetoothPage();else if(state.page==='Privacy')await privacyPage();else if(state.page==='Integrations')await integrationsPage();else if(state.page==='System')await systemPage();else if(state.page==='Logs')await logsPage();else aboutPage()}catch(e){errorView(e)}if(state.page==='Overview')state.timer=setTimeout(refreshOverview,5000)}
function showPage(name){if(state.page==='Baby Monitor'&&name!=='Baby Monitor')stopBabyStream();state.page=name;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$('#page-title').textContent=name;$('#page-subtitle').textContent=descriptions[name];document.body.classList.remove('nav-open');render()}
items.forEach(([name,icon],i)=>{const b=document.createElement('button');b.className='nav-item'+(i?'':' active');b.dataset.page=name;b.innerHTML=`<svg><use href="#${icon}"></use></svg><span>${name}</span>`;b.onclick=()=>showPage(name);nav.appendChild(b)});
$('#reboot').onclick=()=>power('reboot','Reboot');$('#theme').onclick=()=>{const light=document.body.classList.toggle('light');localStorage.setItem('libreecho-theme',light?'light':'dark');$('#theme').textContent=light?'☾':'☼'};$('#menu').onclick=()=>document.body.classList.toggle('nav-open');
if(localStorage.getItem('libreecho-theme')==='light'){document.body.classList.add('light');$('#theme').textContent='☾'}
function updateAuthControl(){const b=$('#auth-control');if(!b)return;if(state.authMode==='development-disabled'){b.textContent='Dev access';b.title='Authentication is disabled for this development image';b.disabled=true;return}b.disabled=false;b.title=state.token?'Sign out':'Sign in';b.textContent=state.token?`${state.username||'Signed in'} · Sign out`:'Sign in'}
function clearSession(){state.token='';state.username='';sessionStorage.removeItem('libreecho-token');sessionStorage.removeItem('libreecho-username');updateAuthControl()}
function openAuthDialog(){const dialog=$('#auth-dialog'),form=$('#auth-form'),copy=$('#auth-copy'),userRow=$('#auth-username-row'),passwordRow=$('#auth-password-row'),tokenRow=$('#auth-token-row'),user=$('#auth-username'),password=$('#auth-password'),token=$('#auth-token'),error=$('#auth-error');if(!dialog||state.authMode==='development-disabled')return Promise.resolve(false);const users=state.authMode==='users';copy.textContent=users?'Use a configured local account to continue.':'Paste the development API token to continue.';userRow.hidden=!users;passwordRow.hidden=!users;tokenRow.hidden=users;user.required=users;password.required=users;token.required=!users;error.hidden=true;error.textContent='';form.reset();if(dialog.showModal)dialog.showModal();else dialog.setAttribute('open','');return new Promise(resolve=>{let finished=false;const finish=ok=>{if(finished)return;finished=true;if(dialog.open)dialog.close();else dialog.removeAttribute('open');form.onsubmit=null;dialog.oncancel=null;$('#auth-cancel').onclick=null;resolve(ok)};$('#auth-cancel').onclick=()=>finish(false);dialog.oncancel=e=>{e.preventDefault();finish(false)};form.onsubmit=async e=>{e.preventDefault();error.hidden=true;try{if(users){const session=await api('/auth/login',{method:'POST',body:JSON.stringify({username:user.value.trim(),password:password.value})});state.token=session.token;state.username=session.username||user.value.trim();sessionStorage.setItem('libreecho-token',state.token);sessionStorage.setItem('libreecho-username',state.username)}else{state.token=token.value.trim();if(!state.token)throw new Error('API token is required');const current=await api('/auth');state.username=current.username||'token';sessionStorage.setItem('libreecho-token',state.token);sessionStorage.setItem('libreecho-username',state.username)}updateAuthControl();finish(true)}catch(err){if(!users)clearSession();error.textContent=err.message||'Authentication failed';error.hidden=false}};return undefined})}
async function ensureAuth(c){state.authMode=c.authentication;updateAuthControl();if(c.authentication==='users'||c.authentication==='bearer-token'){if(state.token){try{const current=await api('/auth');state.username=current.username||state.username||'token';sessionStorage.setItem('libreecho-username',state.username);updateAuthControl();return}catch(_){clearSession()}}if(!await openAuthDialog())throw new Error('Sign in is required to use this device')}}
async function signOut(){if(!state.token)return;try{await api('/auth/logout',{method:'POST',body:'{}'});toast('Signed out')}catch(e){toast(e.message,true)}finally{clearSession();errorView(new Error('Sign in to continue'))}}
$('#auth-control').onclick=()=>state.token?signOut():openAuthDialog().then(ok=>ok?render():undefined).catch(errorView);
api('/config').then(async c=>{state.csrf=c.csrf_token;await ensureAuth(c);return api('/status')}).then(()=>render()).catch(errorView);
