/* Privacy copy reflects configured remote AI endpoints and audio retention. */
async function privacyPage(){
  const pair=await Promise.all([api('/privacy'),api('/assistant').catch(()=>null),api('/voice-pipeline').catch(()=>null),api('/live').catch(()=>null)]),p=pair[0],a=pair[1],pipeline=pair[2],live=pair[3];
  const localStack=a?.provider==='openai-compatible'&&a.enabled,assistantRemote=!!a?.enabled,pipelineCustom=pipeline?.mode==='custom',pipelineHA=pipeline?.mode==='home-assistant',pipelineRemote=pipelineCustom||pipelineHA,liveRemote=live?.enabled===true;
  const unknown=!a||typeof a.enabled!=='boolean'||(a.enabled&&!['openai-compatible','openai-codex'].includes(a.provider))||!['local','custom','home-assistant'].includes(pipeline?.mode)||typeof live?.enabled!=='boolean'||['pending','failed'].includes(pipeline?.restart?.state);
  const mode=p.audio_retention_mode||p.audio_retention||'none',remote=p.audio_remote_destination||{},ha=pipeline?.home_assistant||{};
  const destinations=[];
  if(pipelineCustom)destinations.push(`Microphone audio is sent to ${esc(pipeline.stt?.wyoming_uri||'the configured Whisper service')}; generated reply text is sent to ${esc(pipeline.tts?.wyoming_uri||'the configured Piper service')}.`);
  if(pipelineHA)destinations.push('Microphone audio is sent to the Home Assistant host over ESPHome. Home Assistant determines any further audio and transcript destinations.');
  if(assistantRemote)destinations.push(localStack?`Assistant transcripts are sent to ${esc(a.base_url||'the configured language model')}.`:'Assistant transcripts are sent to ChatGPT.');
  if(liveRemote)destinations.push('Microphone audio is sent to OpenAI Realtime during a GPT-Live conversation, including the short RAM-only wake preroll. Idle microphone audio is not transmitted.');
  const routes=(unknown?'<div class="notice unsupported"><strong>Processing destinations could not be determined</strong><span>One or more voice routing states are unavailable. On-device processing cannot be confirmed; disabling network AI services will stop routes that are known. Retry to confirm any remaining routes.</span></div>':'')+(destinations.length?`<div class="notice unsupported"><strong>Off-device voice processing is configured</strong><span>Wake-word detection stays on this device. ${destinations.join(' ')}</span></div>`:unknown?'':'<div class="privacy-callout">Wake word, speech recognition, and speech output are configured to run on this device.</div>');
  const health='<dl class="facts"><dt>Voice pipeline</dt><dd>'+esc(pipeline?.mode||'Unavailable')+'</dd>'+(pipelineCustom?`<dt>Whisper</dt><dd class="${pipeline.stt?.reachable?'connected':''}">${pipeline.stt?.reachable?'Reachable':'Unavailable'}</dd><dt>Piper</dt><dd class="${pipeline.tts?.reachable?'connected':''}">${pipeline.tts?.reachable?'Reachable':'Unavailable'}</dd>`:'')+`<dt>Language model</dt><dd>${!a?'Unavailable':assistantRemote?esc(localStack?(a.base_url||'Endpoint unavailable'):'ChatGPT'):'Disabled'}</dd>`+(pipelineHA?`<dt>Home Assistant (ESPHome)</dt><dd>${ha.connected?'Connected':ha.ready?'Ready — awaiting Home Assistant':'Unavailable'} · TCP ${esc(ha.port||6053)} · Host not exposed by the API</dd>`:'')+`<dt>GPT-Live</dt><dd>${typeof live?.enabled!=='boolean'?'Unavailable':liveRemote?'Enabled — OpenAI Realtime':'Disabled'}</dd></dl>`;
  const remoteState=mode==='remote'?`<div class="notice unsupported"><strong>Remote retention transport unavailable (${esc(remote.state||'unavailable')})</strong><span>${esc(remote.last_error||'Audio is not stored locally while remote retention is unavailable. No upload is attempted by this release.')}</span></div>`:'';
  const retention=select('Microphone audio retention',mode,'audio-retention-mode',['none','local','remote'])+select('Audio retention duration',`${p.audio_retention_hours||24} hours`,'audio-retention-hours',['24 hours','168 hours','720 hours'])+select('Audio size cap',`${p.audio_retention_max_mb||64} MiB`,'audio-retention-max-mb',['16 MiB','64 MiB','256 MiB'])+field('Remote HTTPS destination',remote.url||'','audio-retention-destination','url','maxlength="255" autocomplete="off" placeholder="https://nas.example/retained-audio"')+remoteState+'<div class="privacy-callout">Remote retention is opt-in and uses an HTTPS destination with credentials supplied out of band. This release has no upload transport, so an unavailable remote target disables retention rather than filling local storage or silently dropping audio.</div>';
  content.innerHTML='<div class="settings-grid">'+panel('Processing',routes+health+toggle('Allow configured network AI services',!p.local_only,'local-only')+toggle('Retain microphone audio',mode!=='none','audio-retention')+toggle('Diagnostic telemetry',p.diagnostic_telemetry,'telemetry')+toggle('Crash reports',p.crash_reports,'crash-reports')+saveButton('save-privacy'))+panel('Retention',retention+select('Log retention',String(p.log_retention_hours)+' hours','retention',['24 hours','168 hours','720 hours'])+ '<div class="privacy-callout">Secrets, API keys, remote credentials, and microphone audio are excluded from configuration exports.</div>'+saveButton('save-retention'))+'</div>';
  bindDirty(['#local-only','#audio-retention','#audio-retention-mode','#audio-retention-hours','#audio-retention-max-mb','#audio-retention-destination','#telemetry','#crash-reports'],'#save-privacy');bindDirty(['#retention','#audio-retention-mode','#audio-retention-hours','#audio-retention-max-mb','#audio-retention-destination'],'#save-retention');
  $('#audio-retention').onchange=()=>{$('#audio-retention-mode').value=$('#audio-retention').checked?(mode==='none'?'local':mode):'none'};
  $('#audio-retention-mode').onchange=()=>{$('#audio-retention').checked=$('#audio-retention-mode').value!=='none'};
  $('#save-privacy').onclick=async()=>{
    if(state.busy)return;
    const allowNetwork=$('#local-only').checked;
    setBusy(true);
    try {
      if(!allowNetwork) {
        if(liveRemote)await api('/live',{method:'PUT',body:JSON.stringify({enabled:false})});
        if(assistantRemote)await api('/assistant',{method:'PUT',body:JSON.stringify({provider:a.provider,enabled:false})});
        if(pipelineRemote) {
          const result=await api('/voice-pipeline',{method:'PUT',body:JSON.stringify({mode:'local',stt_wyoming_uri:pipeline.stt?.wyoming_uri||'',stt_model:pipeline.stt?.model||'whisper-small',tts_wyoming_uri:pipeline.tts?.wyoming_uri||'',tts_voice:pipeline.tts?.voice||'en_GB-alan-medium'})});
          if(result?.restart?.state==='pending')throw new Error('Network voice disable requested; the pipeline transition is pending. Retry after it completes.');
          if(result?.restart?.state==='failed')throw new Error(result.restart.error||'Network voice disable failed.');
        }
      }
      await api('/privacy',{method:'PUT',body:JSON.stringify({local_only:!allowNetwork,audio_retention:$('#audio-retention-mode').value,audio_retention_hours:parseInt($('#audio-retention-hours').value,10),audio_retention_max_mb:parseInt($('#audio-retention-max-mb').value,10),audio_remote_url:$('#audio-retention-destination').value,diagnostic_telemetry:$('#telemetry').checked,crash_reports:$('#crash-reports').checked})});
      toast(allowNetwork?'Network AI services allowed':unknown?'Network AI disabled where routing was known; some routes could not be determined':'Network AI services disabled',!allowNetwork&&unknown);
    } catch(error) { toast(error.message,true); } finally { await privacyPage(); setBusy(false); }
  };
  $('#save-retention').onclick=async()=>{if(state.busy)return;setBusy(true);try{await api('/privacy',{method:'PUT',body:JSON.stringify({audio_retention:$('#audio-retention-mode').value,audio_retention_hours:parseInt($('#audio-retention-hours').value,10),audio_retention_max_mb:parseInt($('#audio-retention-max-mb').value,10),audio_remote_url:$('#audio-retention-destination').value,log_retention_hours:parseInt($('#retention').value,10)})});toast('Retention changes saved')}catch(error){toast(error.message,true)}finally{await privacyPage();setBusy(false)}};
}
