'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const setup={step:0,csrf:'libreecho-local',busy:false,hardwareReady:false,connectivity:null,data:{hostname:'libreecho',ssid:'',security:'wpa2',password:'',volume:64,wake_word:'LibreEcho',wake_sensitivity:68,local_only:true,diagnostic_telemetry:false}};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){const headers={Accept:'application/json',...(opt.body?{'Content-Type':'application/json','X-LibreEcho-CSRF':setup.csrf}:{})};const response=await fetch('/api/v1'+path,{...opt,headers});let body;try{body=await response.json()}catch(_){throw new Error('The device returned an unreadable response')}if(!response.ok||!body.ok)throw new Error(body.error?.message||'Request failed');return body.data}
function error(message=''){const box=$('#setup-error');box.textContent=message;box.hidden=!message;if(message)box.scrollIntoView({behavior:'smooth',block:'start'})}
function sync(){setup.data.hostname=$('#setup-hostname').value.trim();setup.data.ssid=$('#setup-ssid').value.trim();setup.data.security=$('#setup-security').value;setup.data.password=$('#setup-password').value;setup.data.volume=+$('#setup-volume').value;setup.data.wake_word=$('#setup-wake').value;setup.data.wake_sensitivity=+$('#setup-sensitivity').value;setup.data.local_only=$('#setup-local').checked;setup.data.diagnostic_telemetry=$('#setup-telemetry').checked}
function validate(){sync();if(setup.step===1){if(!setup.hardwareReady)throw new Error('The Wi-Fi driver is not ready. Review the hardware status before continuing.');if(!setup.data.ssid)throw new Error('Choose or enter a Wi-Fi network.');if(setup.data.security!=='open'&&setup.data.password.length<8)throw new Error('The Wi-Fi password must contain at least 8 characters.')}if(setup.step===2&&!/^[A-Za-z0-9][A-Za-z0-9-]{0,62}$/.test(setup.data.hostname))throw new Error('Enter a valid hostname using letters, numbers and hyphens.');if(setup.step===4&&!$('#setup-confirm').checked)throw new Error('Confirm that you are ready for the setup network to close.')}
function render(){error();$$('.setup-page').forEach(x=>x.classList.toggle('active',+x.dataset.step===setup.step));$$('[data-step-marker]').forEach(x=>{const n=+x.dataset.stepMarker;x.classList.toggle('active',n===setup.step);x.classList.toggle('done',n<setup.step)});$('#setup-back').hidden=setup.step===0||setup.step===5;$('#step-count').hidden=setup.step===5;$('#step-count').textContent=`Step ${setup.step+1} of 5`;$('#setup-next').hidden=setup.step===5;$('#setup-next').textContent=setup.step===0?'Get started':setup.step===4?'Apply and connect':'Continue';if(setup.step===1&&!$('#wifi-list .wifi-option'))scan();if(setup.step===4)review();if(setup.step===5)$('#setup-actions').hidden=true}
async function scan(){const box=$('#wifi-list');if(!setup.hardwareReady){box.innerHTML='<p class="muted">Wi-Fi scanning is unavailable until the driver registers wlan0.</p>';return}box.innerHTML='<p class="muted">Scanning for networks…</p>';$('#scan-wifi').disabled=true;try{const result=await api('/network/wifi/scan');box.innerHTML=result.networks.length?result.networks.map(n=>`<button type="button" class="wifi-option ${n.ssid===setup.data.ssid?'selected':''}" data-ssid="${esc(n.ssid)}" data-security="${esc(n.security)}"><span><strong>${esc(n.ssid)}</strong><small>${esc(n.security.toUpperCase())}</small></span><span class="signal" aria-label="Signal ${n.signal}%">${'▮'.repeat(Math.max(1,Math.ceil(n.signal/25)))}</span></button>`).join(''):'<p class="muted">No networks found. Enter the SSID manually.</p>';$$('.wifi-option').forEach(button=>button.onclick=()=>{$$('.wifi-option').forEach(x=>x.classList.remove('selected'));button.classList.add('selected');$('#setup-ssid').value=button.dataset.ssid;$('#setup-security').value=button.dataset.security;securityChanged()})}catch(e){box.innerHTML=`<p class="muted">${esc(e.message)} Enter the SSID manually or scan again.</p>`}finally{$('#scan-wifi').disabled=false}}
function renderFirmware(current){setup.connectivity=current;const card=$('#vendor-firmware-state'),button=$('#force-vendor-import'),title=$('#vendor-firmware-title'),detail=$('#vendor-firmware-detail'),fw=current.vendor_firmware||{state:'unavailable',verification:'none',source_layout:'none',error:'status-unavailable',force_next_boot:false};if(current.backend==='mock'){setup.hardwareReady=true;card.hidden=true;return}card.hidden=false;card.classList.remove('ready','warning','failed');setup.hardwareReady=!!current.wlan0_registered;if(setup.hardwareReady){card.classList.add('ready');title.textContent='Wi-Fi driver ready';detail.textContent=`Firmware import ${fw.verification==='hash-pinned'?'hash verified':fw.verification}; wlan0 is registered${fw.source_layout&&fw.source_layout!=='none'?` from ${fw.source_layout}`:''}.`;button.hidden=true;return}if(fw.force_next_boot){card.classList.add('warning');title.textContent='Forced firmware retry scheduled';detail.textContent='The one-shot compatibility import will run on the next boot. It will be reported as unverified.';button.hidden=false;button.disabled=true;button.textContent='Retry scheduled';return}card.classList.add(fw.state==='failed'?'failed':'warning');title.textContent=fw.state==='ready'?'Firmware loaded, but wlan0 is absent':'Wi-Fi firmware import failed';detail.textContent=`Import: ${fw.state}; verification: ${fw.verification}; wlan0: ${current.wlan0_registered?'registered':'absent'}${fw.error&&fw.error!=='none'?`; ${fw.error}`:''}.`;button.hidden=false;button.disabled=false;button.textContent='Force retry next boot'}
function securityChanged(){const open=$('#setup-security').value==='open';$('#password-field').hidden=open;$('#setup-password').required=!open;if(open)$('#setup-password').value=''}
function review(){sync();const items=[['Network',setup.data.ssid],['Security',setup.data.security.toUpperCase()],['Hostname',setup.data.hostname+'.local'],['Initial volume',setup.data.volume+'%'],['Wake word',setup.data.wake_word],['Local processing',setup.data.local_only?'Required':'Optional'],['Diagnostic telemetry',setup.data.diagnostic_telemetry?'Enabled':'Disabled']];$('#setup-review').innerHTML=items.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}
async function complete(){setup.busy=true;$('#setup-next').disabled=true;$('#setup-next').textContent='Applying…';try{await api('/setup',{method:'POST',body:JSON.stringify(setup.data)});$('#control-centre-link').textContent=`http://${setup.data.hostname}.local`;$('#control-centre-link').href=`http://${setup.data.hostname}.local/`;setup.step=5;render()}catch(e){error(e.message);$('#setup-next').disabled=false;$('#setup-next').textContent='Apply and connect'}finally{setup.busy=false}}
$('#setup-next').onclick=()=>{if(setup.busy)return;try{validate();if(setup.step===4){complete();return}setup.step++;render()}catch(e){error(e.message)}};
$('#setup-back').onclick=()=>{if(setup.step>0){setup.step--;render()}};
$('#scan-wifi').onclick=scan;$('#setup-security').onchange=securityChanged;
$('#force-vendor-import').onclick=async()=>{if(!confirm('Schedule one unverified owner-local firmware import for the next boot? Hash matching will be bypassed, but file names, patch routing metadata, and safety limits will still be checked.'))return;const button=$('#force-vendor-import');button.disabled=true;try{await api('/setup/vendor-import-force-next-boot',{method:'POST',body:JSON.stringify({confirm:'force-unverified-owner-local-import'})});setup.connectivity.vendor_firmware.force_next_boot=true;renderFirmware(setup.connectivity)}catch(e){error(e.message);button.disabled=false}};
$('#show-password').onclick=()=>{const field=$('#setup-password'),showing=field.type==='text';field.type=showing?'password':'text';$('#show-password').textContent=showing?'Show':'Hide'};
$('#setup-volume').oninput=e=>$('#volume-output').textContent=e.target.value+'%';$('#setup-sensitivity').oninput=e=>$('#sensitivity-output').textContent=e.target.value+'%';$('#setup-hostname').oninput=e=>$('#hostname-preview').textContent=(e.target.value||'libreecho')+'.local';
Promise.all([api('/config'),api('/setup')]).then(([config,current])=>{setup.csrf=config.csrf_token;if(current.completed){location.replace('/');return}renderFirmware(current);Object.assign(setup.data,{hostname:current.hostname,volume:current.volume,wake_word:current.wake_word,wake_sensitivity:current.wake_sensitivity,local_only:current.local_only,diagnostic_telemetry:current.diagnostic_telemetry});$('#setup-hostname').value=setup.data.hostname;$('#setup-volume').value=setup.data.volume;$('#volume-output').textContent=setup.data.volume+'%';$('#setup-wake').value=setup.data.wake_word;$('#setup-sensitivity').value=setup.data.wake_sensitivity;$('#sensitivity-output').textContent=setup.data.wake_sensitivity+'%';$('#setup-local').checked=setup.data.local_only;$('#setup-telemetry').checked=setup.data.diagnostic_telemetry;$('#hostname-preview').textContent=setup.data.hostname+'.local';render()}).catch(e=>error(e.message));
