#include "backend_internal.h"
#include "config_store.h"
#include "json.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

struct mock_state { struct le_audio_state audio;struct le_led_state led;struct le_network_state net;struct le_wake_word_state wake;struct le_wifi_scan scan;char device_name[64],config_path[384],pending_ssid[64],fail_next[32],power[24];unsigned rng;time_t started,connect_at,recover_at;int temp_base,update_progress; };
static struct mock_state*M(struct le_backend*b){return(struct mock_state*)b->data;} static unsigned rnd(struct mock_state*m){m->rng=m->rng*1103515245u+12345u;return(m->rng>>16)&0x7fff;}
static int save(struct mock_state*m){char j[2048];int n=snprintf(j,sizeof(j),"{\n  \"device_name\": \"%s\",\n  \"hostname\": \"%s\",\n  \"volume\": %d,\n  \"microphone_gain\": %d,\n  \"microphone_muted\": %s,\n  \"led_r\": %u, \"led_g\": %u, \"led_b\": %u,\n  \"led_brightness\": %d,\n  \"wake_word\": \"%s\",\n  \"wake_enabled\": %s,\n  \"wake_sensitivity\": %d,\n  \"wifi_state\": \"%s\",\n  \"wifi_ssid\": \"%s\",\n  \"update_progress\": %d\n}\n",m->device_name,m->net.hostname,m->audio.volume,m->audio.microphone_gain,m->audio.muted?"true":"false",m->led.current.r,m->led.current.g,m->led.current.b,m->led.current.brightness,m->wake.wake_word,m->wake.enabled?"true":"false",m->wake.sensitivity,m->net.state,m->net.ssid,m->update_progress);return m->config_path[0]?config_write_atomic(m->config_path,j,(size_t)n):0;}
static void defaults(struct mock_state*m,unsigned seed){static const char*ssids[]={"LibreNet-5G","LibreNet-IoT","Neighbourhood WiFi","Open Test Network"};static const char*secs[]={"wpa2","wpa2","wpa3","open"};size_t i;memset(m,0,sizeof(*m));m->rng=seed?seed:0x4c454348;m->started=time(0);m->temp_base=47;strcpy(m->power,"online");strcpy(m->device_name,"Kitchen LibreEcho");strcpy(m->net.hostname,"libreecho-dev");strcpy(m->net.state,"connected");strcpy(m->net.ssid,"LibreNet-5G");strcpy(m->net.ip,"192.168.10.42");strcpy(m->net.gateway,"192.168.10.1");strcpy(m->net.dns,"192.168.10.1");m->net.signal=82;m->net.internet=1;m->net.dhcp=1;m->scan.count=4;for(i=0;i<m->scan.count;i++){strcpy(m->scan.networks[i].ssid,ssids[i]);strcpy(m->scan.networks[i].security,secs[i]);m->scan.networks[i].signal=88-(int)i*17;}m->audio.volume=64;m->audio.microphone_gain=70;m->audio.notification_volume=55;m->audio.startup_sound=1;m->audio.amplifier_on=1;m->audio.output_available=1;m->led.current=(struct le_led_profile){72,216,118,72,50};m->led.boot=m->led.current;m->led.listening=(struct le_led_profile){72,185,255,80,50};m->led.thinking=(struct le_led_profile){168,115,239,80,70};m->led.error=(struct le_led_profile){239,80,80,90,40};m->led.dnd=(struct le_led_profile){190,35,35,45,20};strcpy(m->wake.wake_word,"LibreEcho");strcpy(m->wake.model_status,"ready");m->wake.enabled=1;m->wake.sensitivity=68;m->wake.cooldown_ms=1500;m->wake.cpu_cost=8;m->wake.memory_cost_mb=34;}
static void load_profile(struct mock_state*m,const char*p,unsigned cli_seed){char j[16384],*at;int v;size_t count=0;if(!p||config_read(p,j,sizeof(j))<0||!json_valid_object(j,strlen(j)))return;if(json_get_int(j,"temperature_c",&v)>0&&v>=0&&v<=120)m->temp_base=v;if(!cli_seed&&json_get_int(j,"seed",&v)>0)m->rng=(unsigned)v;at=j;while(count<LE_MAX_WIFI&&(at=strstr(at,"\"ssid\""))){char object[512],*end=strchr(at,'}');size_t n;if(!end)break;n=(size_t)(end-at+1);if(n>=sizeof(object)){at=end+1;continue;}memcpy(object,at,n);object[n]=0;if(json_get_string(object,"ssid",m->scan.networks[count].ssid,sizeof(m->scan.networks[count].ssid))>0){if(json_get_string(object,"security",m->scan.networks[count].security,sizeof(m->scan.networks[count].security))<1)strcpy(m->scan.networks[count].security,"wpa2");if(json_get_int(object,"signal",&v)<1)v=60;m->scan.networks[count].signal=v<0?0:v>100?100:v;count++;}at=end+1;}if(count)m->scan.count=count;}
static void load(struct mock_state*m,const char*p){char j[16384],s[128];int v;if(!p||config_read(p,j,sizeof(j))<0||!json_valid_object(j,strlen(j)))return;if(json_get_string(j,"device_name",s,sizeof(s))>0)strcpy(m->device_name,s);if(json_get_string(j,"hostname",s,sizeof(s))>0)strcpy(m->net.hostname,s);if(json_get_int(j,"volume",&v)>0&&v>=0&&v<=100)m->audio.volume=v;if(json_get_int(j,"microphone_gain",&v)>0&&v>=0&&v<=100)m->audio.microphone_gain=v;if(json_get_bool(j,"microphone_muted",&v)>0)m->audio.muted=v;if(json_get_int(j,"led_r",&v)>0&&v>=0&&v<=255)m->led.current.r=(uint8_t)v;if(json_get_int(j,"led_g",&v)>0&&v>=0&&v<=255)m->led.current.g=(uint8_t)v;if(json_get_int(j,"led_b",&v)>0&&v>=0&&v<=255)m->led.current.b=(uint8_t)v;if(json_get_int(j,"led_brightness",&v)>0&&v>=0&&v<=100)m->led.current.brightness=v;if(json_get_string(j,"wake_word",s,sizeof(s))>0)strcpy(m->wake.wake_word,s);if(json_get_bool(j,"wake_enabled",&v)>0)m->wake.enabled=v;if(json_get_int(j,"wake_sensitivity",&v)>0&&v>=0&&v<=100)m->wake.sensitivity=v;}
static int fail(struct mock_state*m,const char*op){if(!strcmp(m->fail_next,op)){m->fail_next[0]=0;return 1;}return 0;}
static void mock_cpu_status(struct mock_state*m,struct le_system_status*o){size_t i;o->cpu_count=4;for(i=0;i<o->cpu_count;i++){o->cpus[i].online=1;o->cpus[i].utilization=12+(int)(rnd(m)%36);o->cpus[i].frequency_khz=1200000+(int)(rnd(m)%4)*100000;}}
static void destroy(struct le_backend*b){save(M(b));free(b->data);}static int status(struct le_backend*b,struct le_system_status*o){struct mock_state*m=M(b);int drift=(int)(rnd(m)%7)-3;memset(o,0,sizeof(*o));o->uptime=difftime(time(0),m->started);o->cpu=14+(int)(rnd(m)%18);o->memory=44+(int)(rnd(m)%5);o->storage=19;o->temperature=m->temp_base+drift;o->memory_total_mb=512;o->memory_used_mb=o->memory_total_mb*o->memory/100;o->storage_total_mb=4096;o->storage_used_mb=o->storage_total_mb*o->storage/100;strcpy(o->device_state,m->power);mock_cpu_status(m,o);return LE_OK;}
static int device(struct le_backend*b,struct le_device_info*o){struct mock_state*m=M(b);memset(o,0,sizeof(*o));strcpy(o->name,m->device_name);strcpy(o->hostname,m->net.hostname);strcpy(o->model,"Amazon Echo (2nd generation)");strcpy(o->serial,"DEV-MOCK-4C454348");strcpy(o->os_version,"LibreEcho OS 0.1.0-dev");strcpy(o->kernel,"3.18-compatible mock");strcpy(o->hardware_revision,"MT8163 development profile");strcpy(o->backend,"mock");return LE_OK;}
static int audio(struct le_backend*b,struct le_audio_state*o){*o=M(b)->audio;return LE_OK;}static int volume(struct le_backend*b,int v){if(v<0||v>100)return LE_INVALID;if(fail(M(b),"audio"))return LE_IO;M(b)->audio.volume=v;return save(M(b));}static int gain(struct le_backend*b,int v){if(v<0||v>100)return LE_INVALID;M(b)->audio.microphone_gain=v;return save(M(b));}static int mute(struct le_backend*b,int v){M(b)->audio.muted=!!v;return save(M(b));}static int tone(struct le_backend*b){return fail(M(b),"audio-test")?LE_IO:LE_OK;}
static int led(struct le_backend*b,struct le_led_state*o){*o=M(b)->led;return LE_OK;}static int colour(struct le_backend*b,uint8_t r,uint8_t g,uint8_t bl){if(fail(M(b),"led"))return LE_IO;M(b)->led.current.r=r;M(b)->led.current.g=g;M(b)->led.current.b=bl;return save(M(b));}static int brightness(struct le_backend*b,int v){if(v<0||v>100)return LE_INVALID;M(b)->led.current.brightness=v;return save(M(b));}static int boot_led(struct le_backend*b,const struct le_led_profile*p){M(b)->led.boot=*p;return save(M(b));}static int led_test(struct le_backend*b){return fail(M(b),"led-test")?LE_IO:LE_OK;}
static int network(struct le_backend*b,struct le_network_state*o){*o=M(b)->net;return LE_OK;}static int scan(struct le_backend*b,struct le_wifi_scan*o){size_t i;if(fail(M(b),"wifi-scan"))return LE_IO;*o=M(b)->scan;for(i=0;i<o->count;i++){o->networks[i].signal+=(int)(rnd(M(b))%7)-3;if(o->networks[i].signal<0)o->networks[i].signal=0;if(o->networks[i].signal>100)o->networks[i].signal=100;}return LE_OK;}
static int connect_wifi(struct le_backend*b,const struct le_wifi_credentials*c){struct mock_state*m=M(b);if(!c->ssid[0])return LE_INVALID;if(fail(m,"wifi-connect")||!strcmp(c->ssid,"FailNet")){strcpy(m->net.state,"failed");m->recover_at=time(0)+4;return LE_IO;}strcpy(m->net.state,"connecting");strncpy(m->pending_ssid,c->ssid,63);m->connect_at=time(0)+2;m->net.internet=0;return LE_OK;}static int disconnect_wifi(struct le_backend*b){struct mock_state*m=M(b);strcpy(m->net.state,"disconnected");m->net.ssid[0]=m->net.ip[0]=0;m->net.signal=m->net.internet=0;return save(m);}static int hostname(struct le_backend*b,const char*s){size_t i,n=strlen(s);if(n<1||n>63)return LE_INVALID;for(i=0;i<n;i++)if(!((s[i]>='a'&&s[i]<='z')||(s[i]>='0'&&s[i]<='9')||s[i]=='-'))return LE_INVALID;strcpy(M(b)->net.hostname,s);return save(M(b));}
static int wake(struct le_backend*b,struct le_wake_word_state*o){*o=M(b)->wake;return LE_OK;}static int wake_set(struct le_backend*b,const char*s){if(!s[0]||strlen(s)>=LE_TEXT)return LE_INVALID;strcpy(M(b)->wake.wake_word,s);return save(M(b));}static int sensitivity(struct le_backend*b,int v){if(v<0||v>100)return LE_INVALID;M(b)->wake.sensitivity=v;return save(M(b));}static int wake_test(struct le_backend*b){if(!M(b)->wake.enabled)return LE_BUSY;M(b)->wake.detected_count++;return LE_OK;}
static int reboot(struct le_backend*b){struct mock_state*m=M(b);strcpy(m->power,"rebooting");m->recover_at=time(0)+3;return LE_OK;}static int shutdown(struct le_backend*b){strcpy(M(b)->power,"shutting_down");return LE_OK;}static int reset(struct le_backend*b){char p[384];unsigned seed=M(b)->rng;strcpy(p,M(b)->config_path);defaults(M(b),seed);strcpy(M(b)->config_path,p);return save(M(b));}
static int tick(struct le_backend*b){struct mock_state*m=M(b);time_t now=time(0);if(m->connect_at&&now>=m->connect_at){m->connect_at=0;strcpy(m->net.state,"connected");strcpy(m->net.ssid,m->pending_ssid);strcpy(m->net.ip,"192.168.10.42");m->net.signal=76;m->net.internet=1;save(m);}if(m->recover_at&&now>=m->recover_at){m->recover_at=0;if(!strcmp(m->power,"rebooting")){strcpy(m->power,"online");m->started=now;}if(!strcmp(m->net.state,"failed"))strcpy(m->net.state,"disconnected");}return LE_OK;}
static int control(struct le_backend*b,const char*a,const char*v){struct mock_state*m=M(b);if(!strcmp(a,"set-temperature")){int n=atoi(v);if(n<0||n>120)return LE_INVALID;m->temp_base=n;}else if(!strcmp(a,"set-wifi")){if(strcmp(v,"connected")&&strcmp(v,"disconnected")&&strcmp(v,"failed"))return LE_INVALID;strcpy(m->net.state,v);m->net.internet=!strcmp(v,"connected");}else if(!strcmp(a,"fail-next")){if(strlen(v)>=sizeof(m->fail_next))return LE_INVALID;strcpy(m->fail_next,v);}else if(!strcmp(a,"trigger")&&!strcmp(v,"wake-word")){m->wake.detected_count++;}else if(!strcmp(a,"set-update-progress")){int n=atoi(v);if(n<0||n>100)return LE_INVALID;m->update_progress=n;}else if(!strcmp(a,"reset"))return reset(b);else return LE_INVALID;return save(m);}
static const struct le_backend_ops ops={destroy,status,device,audio,volume,gain,mute,tone,led,colour,brightness,boot_led,led_test,network,scan,connect_wifi,disconnect_wifi,hostname,wake,wake_set,sensitivity,wake_test,reboot,shutdown,reset,tick,control};
int le_mock_create(struct le_backend*b,const char*mock,const char*cfg,unsigned seed){struct mock_state*m=calloc(1,sizeof(*m));if(!m)return LE_IO;defaults(m,seed);load_profile(m,mock,seed);if(cfg){strncpy(m->config_path,cfg,sizeof(m->config_path)-1);load(m,cfg);}b->data=m;b->ops=&ops;return LE_OK;}
