/* Boot-slot diagnostics: read the records libreecho-init writes to userdata.
 *
 * Every value is bounded and every string is filtered to a safe token set
 * before it reaches JSON, because the record is intentionally shareable
 * evidence: the diagnostic bundle carries it off the device.  Nothing here may
 * allocate, and no field may be trusted for length. */

#include "boot_control.h"

#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#define LE_BOOT_CONTROL_RECORD_MAX 1024
#define LE_BOOT_CONTROL_NUMBER_MAX 9999
#define LE_BOOT_CONTROL_COUNT_MAX 10000000

static const char *update_root(void)
{
    const char *path = getenv("LIBREECHO_UPDATE_ROOT");
    return path && path[0] ? path : "/data/libreecho/update";
}

static int join_path(char *out, size_t out_size, const char *name)
{
    int n = snprintf(out, out_size, "%s/%s", update_root(), name);
    return n > 0 && (size_t)n < out_size;
}

static int read_regular(const char *path, char *out, size_t out_size)
{
    int fd;
    ssize_t n;
    size_t used = 0;
    struct stat st;
    if (!out_size)
        return 0;
    out[0] = '\0';
    fd = open(path, O_RDONLY | O_NONBLOCK | O_CLOEXEC | O_NOFOLLOW);
    if (fd < 0)
        return 0;
    if (fstat(fd, &st) || !S_ISREG(st.st_mode)) {
        close(fd);
        return 0;
    }
    while (used + 1 < out_size) {
        n = read(fd, out + used, out_size - used - 1);
        if (n < 0) {
            close(fd);
            out[0] = '\0';
            return 0;
        }
        if (n == 0)
            break;
        used += (size_t)n;
    }
    out[used] = '\0';
    close(fd);
    return 1;
}

/* Copy one `key=value` line's value out of a flat record.  The key is matched
   at the start of a line and must be followed by '=', so a suffix key cannot
   match a longer one (slot_a_tries vs tries). */
static int field_value(const char *text, const char *key, char *out, size_t out_size)
{
    size_t key_len = strlen(key);
    const char *line = text;
    if (!out_size)
        return 0;
    out[0] = '\0';
    while (line && *line) {
        const char *end = strchr(line, '\n');
        size_t line_len = end ? (size_t)(end - line) : strlen(line);
        if (line_len > key_len && !strncmp(line, key, key_len) && line[key_len] == '=') {
            size_t value_len = line_len - key_len - 1;
            size_t i;
            if (value_len >= out_size)
                value_len = out_size - 1;
            for (i = 0; i < value_len; ++i) {
                char c = line[key_len + 1 + i];
                if (c == '\r')
                    break;
                out[i] = c;
            }
            out[i] = '\0';
            return 1;
        }
        line = end ? end + 1 : NULL;
    }
    return 0;
}

static int field_int(const char *text, const char *key, int fallback)
{
    char raw[LE_BOOT_CONTROL_TEXT];
    size_t i;
    long value = 0;
    if (!field_value(text, key, raw, sizeof(raw)) || !raw[0])
        return fallback;
    for (i = 0; raw[i]; ++i) {
        if (raw[i] < '0' || raw[i] > '9')
            return fallback;
        value = value * 10 + (raw[i] - '0');
        if (value > LE_BOOT_CONTROL_NUMBER_MAX)
            return fallback;
    }
    return (int)value;
}

/* The boot counter is a bare integer on its own line. */
static int plain_int(const char *text)
{
    size_t i = 0;
    long value = 0;
    if (!text || !text[0])
        return -1;
    while (text[i] && text[i] != '\n' && text[i] != '\r') {
        if (text[i] < '0' || text[i] > '9')
            return -1;
        value = value * 10 + (text[i] - '0');
        if (value > LE_BOOT_CONTROL_COUNT_MAX)
            return -1;
        ++i;
    }
    return i ? (int)value : -1;
}

/* Recorded tokens are generated by init from a fixed vocabulary; anything else
   is dropped to '-' rather than forwarded. */
static void safe_token(char *out, size_t out_size, const char *value)
{
    size_t used = 0;
    size_t i;
    if (!out_size)
        return;
    if (!value || !value[0]) {
        snprintf(out, out_size, "-");
        return;
    }
    for (i = 0; value[i] && used + 1 < out_size; ++i) {
        char c = value[i];
        if ((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' ||
            c == '_' || c == '.')
            out[used++] = c;
    }
    out[used] = '\0';
    if (!used)
        snprintf(out, out_size, "-");
}

/* State, mode and slot values decide how the API and the UI describe a device,
   so they are matched against the vocabulary init can actually write instead of
   being passed through. */
static void safe_choice(char *out, size_t out_size, const char *value,
                        const char *const *allowed, size_t allowed_count,
                        const char *fallback)
{
    size_t i;
    if (!out_size)
        return;
    for (i = 0; value && i < allowed_count; ++i) {
        if (!strcmp(value, allowed[i])) {
            snprintf(out, out_size, "%s", allowed[i]);
            return;
        }
    }
    snprintf(out, out_size, "%s", fallback);
}

/* History lines are rendered as text for a human reader, so keep only the
   characters init can write and drop anything else. */
static void safe_line(char *out, size_t out_size, const char *value)
{
    size_t used = 0;
    size_t i;
    if (!out_size)
        return;
    if (!value) {
        out[0] = '\0';
        return;
    }
    for (i = 0; value[i] && used + 1 < out_size; ++i) {
        char c = value[i];
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') || c == '=' || c == '-' || c == '_' ||
            c == '.' || c == '/' || c == ':' || c == ',')
            out[used++] = c;
    }
    out[used] = '\0';
}

static void read_history(struct le_boot_control *value)
{
    char path[512];
    char text[LE_BOOT_CONTROL_HISTORY_MAX * LE_BOOT_CONTROL_HISTORY_LINE];
    const char *line;
    value->history_count = 0;
    if (!join_path(path, sizeof(path), "boot-history"))
        return;
    if (!read_regular(path, text, sizeof(text)))
        return;
    line = text;
    while (line && *line && value->history_count < LE_BOOT_CONTROL_HISTORY_MAX) {
        const char *end = strchr(line, '\n');
        size_t line_len = end ? (size_t)(end - line) : strlen(line);
        if (line_len) {
            char bounded[LE_BOOT_CONTROL_HISTORY_LINE];
            size_t copy = line_len < sizeof(bounded) - 1 ? line_len : sizeof(bounded) - 1;
            memcpy(bounded, line, copy);
            bounded[copy] = '\0';
            safe_line(value->history[value->history_count], LE_BOOT_CONTROL_HISTORY_LINE,
                      bounded);
            if (value->history[value->history_count][0])
                value->history_count++;
        }
        line = end ? end + 1 : NULL;
    }
}

static void read_slot_state(const char *text, const char *slot, int *priority,
                            int *tries, int *success)
{
    char key[LE_BOOT_CONTROL_TEXT];
    snprintf(key, sizeof(key), "slot_%s_priority", slot);
    *priority = field_int(text, key, -1);
    snprintf(key, sizeof(key), "slot_%s_tries", slot);
    *tries = field_int(text, key, -1);
    snprintf(key, sizeof(key), "slot_%s_success", slot);
    *success = field_int(text, key, -1);
}

void le_boot_control_read(struct le_boot_control *value)
{
    static const char *const states[] = {"booting", "pending", "confirmed", "failed",
                                         "restarting", "skipped"};
    static const char *const modes[] = {"first-boot", "ota", "none"};
    static const char *const slots[] = {"a", "b"};
    char path[512];
    char text[LE_BOOT_CONTROL_RECORD_MAX];
    char raw[LE_BOOT_CONTROL_TEXT];
    if (!value)
        return;
    memset(value, 0, sizeof(*value));
    snprintf(value->state, sizeof(value->state), "unavailable");
    snprintf(value->mode, sizeof(value->mode), "none");
    snprintf(value->running_slot, sizeof(value->running_slot), "-");
    snprintf(value->selected_slot, sizeof(value->selected_slot), "-");
    snprintf(value->pending_slot, sizeof(value->pending_slot), "-");
    snprintf(value->last_check, sizeof(value->last_check), "-");
    value->slot_a_priority = value->slot_b_priority = -1;
    value->slot_a_tries = value->slot_b_tries = -1;
    value->slot_a_success = value->slot_b_success = -1;
    value->running_slot_tries = -1;
    value->running_slot_success = -1;
    read_history(value);
    if (join_path(path, sizeof(path), "boot-health") && read_regular(path, text, sizeof(text))) {
        value->available = 1;
        if (field_value(text, "state", raw, sizeof(raw)))
            safe_choice(value->state, sizeof(value->state), raw, states,
                        sizeof(states) / sizeof(states[0]), "unknown");
        if (field_value(text, "mode", raw, sizeof(raw)))
            safe_choice(value->mode, sizeof(value->mode), raw, modes,
                        sizeof(modes) / sizeof(modes[0]), "unknown");
        if (field_value(text, "running_slot", raw, sizeof(raw)))
            safe_choice(value->running_slot, sizeof(value->running_slot), raw, slots,
                        sizeof(slots) / sizeof(slots[0]), "-");
        if (field_value(text, "selected_slot", raw, sizeof(raw)))
            safe_choice(value->selected_slot, sizeof(value->selected_slot), raw, slots,
                        sizeof(slots) / sizeof(slots[0]), "-");
        if (field_value(text, "pending_slot", raw, sizeof(raw)))
            safe_choice(value->pending_slot, sizeof(value->pending_slot), raw, slots,
                        sizeof(slots) / sizeof(slots[0]), "-");
        if (field_value(text, "last_check", raw, sizeof(raw)))
            safe_token(value->last_check, sizeof(value->last_check), raw);
        read_slot_state(text, "a", &value->slot_a_priority, &value->slot_a_tries,
                        &value->slot_a_success);
        read_slot_state(text, "b", &value->slot_b_priority, &value->slot_b_tries,
                        &value->slot_b_success);
        value->boot_count = field_int(text, "boot_count", 0);
        value->attempt = field_int(text, "attempt", 0);
        value->passed = field_int(text, "passed", 0);
        value->strict_graph = field_int(text, "strict_graph", 0) == 1;
        value->confirmed = !strcmp(value->state, "confirmed");
        if (!strcmp(value->running_slot, "a")) {
            value->running_slot_tries = value->slot_a_tries;
            value->running_slot_success = value->slot_a_success;
        } else if (!strcmp(value->running_slot, "b")) {
            value->running_slot_tries = value->slot_b_tries;
            value->running_slot_success = value->slot_b_success;
        }
    }
    /* The counter is written before the record and survives a boot that never
       reaches the health worker, so it is the fallback identity. */
    if (join_path(path, sizeof(path), "boot-count") && read_regular(path, text, sizeof(text))) {
        int count = plain_int(text);
        if (count >= 0 && !value->boot_count)
            value->boot_count = count;
    }
}

int le_boot_control_json(char *out, size_t out_size, const struct le_boot_control *value)
{
    size_t used = 0;
    int n;
    size_t i;
    if (!out || !out_size || !value)
        return -1;
    out[0] = '\0';
    n = snprintf(out, out_size,
                 "{\"available\":%s,\"state\":\"%s\",\"mode\":\"%s\",\"confirmed\":%s,"
                 "\"running_slot\":\"%s\",\"selected_slot\":\"%s\",\"pending_slot\":\"%s\","
                 "\"boot_count\":%d,\"attempt\":%d,\"passed\":%d,\"last_check\":\"%s\","
                 "\"strict_graph\":%s,\"running_slot_tries\":%d,\"running_slot_success\":%d,"
                 "\"slot_a\":{\"priority\":%d,\"tries\":%d,\"success\":%d},"
                 "\"slot_b\":{\"priority\":%d,\"tries\":%d,\"success\":%d},"
                 "\"history\":[",
                 value->available ? "true" : "false", value->state, value->mode,
                 value->confirmed ? "true" : "false", value->running_slot,
                 value->selected_slot, value->pending_slot, value->boot_count,
                 value->attempt, value->passed, value->last_check,
                 value->strict_graph ? "true" : "false", value->running_slot_tries,
                 value->running_slot_success, value->slot_a_priority, value->slot_a_tries,
                 value->slot_a_success, value->slot_b_priority, value->slot_b_tries,
                 value->slot_b_success);
    if (n < 0 || (size_t)n >= out_size)
        return -1;
    used = (size_t)n;
    for (i = 0; i < value->history_count; ++i) {
        n = snprintf(out + used, out_size - used, "%s\"%s\"", i ? "," : "",
                     value->history[i]);
        if (n < 0 || (size_t)n >= out_size - used)
            return -1;
        used += (size_t)n;
    }
    n = snprintf(out + used, out_size - used, "]}");
    if (n < 0 || (size_t)n >= out_size - used)
        return -1;
    return 0;
}
